package com.milano.quotation.migration;

import com.milano.quotation.common.AppException;
import com.milano.quotation.finance.FinanceMigrationService;
import com.milano.quotation.logistics.LogisticsService;
import com.milano.quotation.purchase.PurchaseProductService;
import com.milano.quotation.quote.QuotationMigrationService;
import com.milano.quotation.storage.AssetObject;
import com.milano.quotation.storage.AssetStorageService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.node.JsonNodeFactory;

import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class BusinessMigrationExecutorTest {
    private PurchaseProductService purchase;private FinanceMigrationService finance;private LogisticsService logistics;private QuotationMigrationService quotations;private AssetStorageService storage;private BusinessMigrationExecutor executor;
    @BeforeEach void setup(){purchase=mock(PurchaseProductService.class);finance=mock(FinanceMigrationService.class);logistics=mock(LogisticsService.class);quotations=mock(QuotationMigrationService.class);storage=mock(AssetStorageService.class);executor=new BusinessMigrationExecutor(purchase,finance,logistics,quotations,storage);when(logistics.importMigrationDrafts(any(),anyString())).thenReturn(JsonNodeFactory.instance.objectNode().put("versionsCreated",1));}
    @Test void permanentlyExcludesTestAndGeneratedSkus(){assertTrue(BusinessMigrationExecutor.permanentlyExcludedSku("TESTP260001"));assertTrue(BusinessMigrationExecutor.permanentlyExcludedSku("AUTO-123"));assertTrue(BusinessMigrationExecutor.permanentlyExcludedSku("DEMO1"));assertFalse(BusinessMigrationExecutor.permanentlyExcludedSku("MLN-REAL-001"));}
    @Test void recognizesExplicitDemoMarkersWithoutRejectingNormalChineseData(){var demo=JsonNodeFactory.instance.objectNode().put("sku","ABC").put("notes","UAT测试");var real=JsonNodeFactory.instance.objectNode().put("sku","ABC").put("notes","真实采购资料");assertTrue(BusinessMigrationExecutor.looksLikeTest(demo));assertFalse(BusinessMigrationExecutor.looksLikeTest(real));}
    @Test void executesApprovedRealProductAndSkipsPermanentTestData(){var batch=batch("purchase",JsonNodeFactory.instance.arrayNode().addObject().put("sku","MLN-REAL-1").put("category","服装"));when(purchase.exists("MLN-REAL-1")).thenReturn(false);var result=executor.execute(batch,"ADMIN");assertEquals(1,result.path("productsCreated").asInt());verify(purchase).upsertImported(argThat(node->"MLN-REAL-1".equals(node.path("sku").asText())),isNull(),isNull());var testBatch=batch("purchase",JsonNodeFactory.instance.arrayNode().addObject().put("sku","TESTP260001"));assertEquals(0,executor.execute(testBatch,"ADMIN").path("productsCreated").asInt());}
    @Test void stagesAndPublishesBrowserImages(){var png="data:image/png;base64,iVBORw0KGgo=";var value=JsonNodeFactory.instance.arrayNode();value.addObject().put("sku","MLN-IMG-1").put("productImage",png);var asset=mock(AssetObject.class);asset.id=UUID.randomUUID();asset.sha256="a".repeat(64);asset.createdAt=Instant.now();when(storage.storeTemporaryImageIndependent(any(),anyString(),any())).thenReturn(asset);var result=executor.execute(batch("purchase",value),"ADMIN");assertEquals(1,result.path("assetsPublished").asInt());verify(storage).publish(argThat(ids->ids.contains(asset.id)));}
    @Test void blocksConflictingProductionSkuButAllowsSameSourceRetry(){var batch=batch("purchase",JsonNodeFactory.instance.arrayNode().addObject().put("sku","MLN-1"));when(purchase.exists("MLN-1")).thenReturn(true);when(purchase.get("MLN-1")).thenReturn(JsonNodeFactory.instance.objectNode().put("legacyMigrationSource","different"));assertThrows(AppException.class,()->executor.execute(batch,"ADMIN"));when(purchase.get("MLN-1")).thenReturn(JsonNodeFactory.instance.objectNode().put("legacyMigrationSource",batch.sourceHash));assertEquals(0,executor.execute(batch,"ADMIN").path("productsCreated").asInt());}
    @Test void routesFinanceLogisticsTemplatesAndRecords(){var financeBatch=batch("finance",JsonNodeFactory.instance.objectNode().put("usdCny",7.2),"milano.finance-exchange-rate.v1");when(finance.apply(eq("exchange-rate"),any(),eq(false))).thenReturn(JsonNodeFactory.instance.objectNode().put("key","exchange-rate").put("changed",true));assertEquals(1,executor.execute(financeBatch,"ADMIN").path("financeChanged").asInt());var logisticsBatch=batch("logistics",JsonNodeFactory.instance.objectNode().put("rows",1));assertEquals(1,executor.execute(logisticsBatch,"ADMIN").path("logistics").path("versionsCreated").asInt());var templates=batch("quotation-template",JsonNodeFactory.instance.arrayNode());when(quotations.applyTemplates(any(),any(),eq("ADMIN"),anyString())).thenReturn(JsonNodeFactory.instance.objectNode().set("createdTemplates",JsonNodeFactory.instance.arrayNode()));executor.execute(templates,"ADMIN");verify(quotations).applyTemplates(any(),any(),eq("ADMIN"),anyString());var records=batch("quotation-record",JsonNodeFactory.instance.arrayNode());when(quotations.applyRecords(any(),any(),eq("ADMIN"),anyString())).thenReturn(JsonNodeFactory.instance.objectNode().set("createdQuotations",JsonNodeFactory.instance.arrayNode()));executor.execute(records,"ADMIN");verify(quotations).applyRecords(any(),any(),eq("ADMIN"),anyString());}
    @Test void rejectsUnsupportedCategoriesAndMissingWhitelist(){var batch=batch("customer",JsonNodeFactory.instance.arrayNode());assertThrows(AppException.class,()->executor.execute(batch,"ADMIN"));((tools.jackson.databind.node.ObjectNode)batch.report).remove("approvedEntryKeys");assertThrows(AppException.class,()->executor.execute(batch,"ADMIN"));}
    @Test void rollsBackEveryCreatedResource(){var batch=new BusinessMigrationBatch();batch.id=UUID.randomUUID();batch.status="completed";var report=JsonNodeFactory.instance.objectNode();var execution=report.putObject("execution");execution.putArray("createdSkus").add("MLN-1");execution.putArray("assetIds").add(UUID.randomUUID().toString());execution.putArray("financeChanges");execution.putObject("logistics");execution.putObject("quotations");batch.report=report;when(logistics.rollbackMigration(any())).thenReturn(JsonNodeFactory.instance.objectNode());when(quotations.rollback(any())).thenReturn(JsonNodeFactory.instance.objectNode());var result=executor.rollback(batch);assertEquals(1,result.path("productsRemoved").asInt());verify(purchase).delete("MLN-1");verify(finance).rollback(any());verify(storage).retire(any(),eq(batch.id));}
    private BusinessMigrationBatch batch(String category,tools.jackson.databind.JsonNode value){return batch(category,value,category+"-key");}
    private BusinessMigrationBatch batch(String category,tools.jackson.databind.JsonNode value,String key){var batch=new BusinessMigrationBatch();batch.id=UUID.randomUUID();batch.sourceHash="f".repeat(64);var report=JsonNodeFactory.instance.objectNode();var entry=report.putArray("entries").addObject();entry.put("source","localStorage").put("container","http://localhost:5173").put("key",key).put("category",category).put("decision","migrate").set("value",value);report.putArray("approvedEntryKeys").add("localStorage/"+key);report.putObject("ownerMappings");report.putObject("conflictResolutions");batch.report=report;return batch;}
}
