package com.milano.quotation.logistics;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.milano.quotation.common.AppException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;import java.util.*;

@Service
public class LogisticsService{
    private final LogisticsProviderRepository providers;private final LogisticsChannelRepository channels;private final LogisticsVersionRepository versions;
    public LogisticsService(LogisticsProviderRepository providers,LogisticsChannelRepository channels,LogisticsVersionRepository versions){this.providers=providers;this.channels=channels;this.versions=versions;}
    @Transactional(readOnly=true) public Workspace workspace(){return new Workspace(providers.findAllByOrderByUpdatedAtDesc().stream().map(this::providerView).toList(),channels.findAllByOrderByUpdatedAtDesc().stream().map(this::channelView).toList(),versions.findAllByOrderByCreatedAtDesc().stream().map(this::versionView).toList());}
    @Transactional public JsonNode addProvider(ObjectNode body){var name=required(body,"name",120);var code=required(body,"code",64).toUpperCase(Locale.ROOT);if(providers.existsByCodeIgnoreCase(code))throw AppException.conflict("物流商编码已存在");var now=Instant.now();var row=new LogisticsProviderEntity();row.id=UUID.randomUUID();row.code=code;var payload=body.deepCopy();payload.put("id",row.id.toString());payload.put("name",name);payload.put("code",code);payload.put("enabled",body.path("enabled").asBoolean(true));payload.put("createdAt",now.toString());payload.put("updatedAt",now.toString());row.payload=payload;row.createdAt=now;row.updatedAt=now;providers.save(row);return providerView(row);}
    @Transactional public JsonNode addChannel(ObjectNode body){var providerId=uuid(body.path("providerId").asText(),"物流商不存在");if(!providers.existsById(providerId))throw AppException.notFound("物流商不存在");var name=required(body,"name",120);var code=required(body,"code",96).toUpperCase(Locale.ROOT);if(channels.existsByCodeIgnoreCase(code))throw AppException.conflict("渠道编码已存在");var now=Instant.now();var row=new LogisticsChannelEntity();row.id=UUID.randomUUID();row.providerId=providerId;row.code=code;row.ruleId=channels.findAll().stream().mapToInt(item->item.ruleId).max().orElse(0)+1;var payload=body.deepCopy();payload.put("id",row.id.toString());payload.put("ruleId",row.ruleId);payload.put("providerId",providerId.toString());payload.put("name",name);payload.put("code",code);payload.put("enabled",body.path("enabled").asBoolean(true));payload.put("currentVersionId","");payload.put("createdAt",now.toString());payload.put("updatedAt",now.toString());row.payload=payload;row.createdAt=now;row.updatedAt=now;channels.save(row);return channelView(row);}
    @Transactional public JsonNode createDraft(UUID channelId,ObjectNode body){var channel=channels.findById(channelId).orElseThrow(()->AppException.notFound("物流渠道不存在"));var sourceHash=required(body,"sourceHash",128);var duplicate=versions.findByChannelIdAndSourceHash(channelId,sourceHash);if(duplicate.isPresent())return versionView(duplicate.get());var now=Instant.now();var row=new LogisticsVersionEntity();row.id=UUID.randomUUID();row.channelId=channelId;row.versionNumber=versions.findByChannelIdOrderByVersionNumberDesc(channelId).stream().mapToInt(v->v.versionNumber).max().orElse(0)+1;row.status="draft";row.sourceHash=sourceHash;var payload=body.deepCopy();payload.put("id",row.id.toString());payload.put("channelId",channelId.toString());payload.put("versionNumber",row.versionNumber);payload.put("status","draft");payload.put("importedAt",now.toString());payload.put("publishedAt","");row.payload=payload;row.createdAt=now;versions.save(row);return versionView(row);}
    @Transactional public JsonNode publish(UUID channelId,UUID versionId,String note,String actor){var channel=channels.findById(channelId).orElseThrow(()->AppException.notFound("物流渠道不存在"));var target=versions.findById(versionId).orElseThrow(()->AppException.notFound("物流版本不存在"));if(!target.channelId.equals(channelId))throw AppException.conflict("版本不属于该渠道");var now=Instant.now();versions.findByChannelIdOrderByVersionNumberDesc(channelId).stream().filter(v->v.status.equals("published")).forEach(v->{v.status="superseded";((ObjectNode)v.payload).put("status","superseded");});target.status="published";target.publishedAt=now;var payload=(ObjectNode)target.payload;payload.put("status","published");payload.put("publishedAt",now.toString());payload.put("publishedBy",actor);payload.put("auditNote",note==null?"":note.trim());channel.currentVersionId=target.id;channel.updatedAt=now;var channelPayload=(ObjectNode)channel.payload;channelPayload.put("currentVersionId",target.id.toString());channelPayload.put("updatedAt",now.toString());return versionView(target);}
    @Transactional public JsonNode rollback(UUID channelId,UUID targetId,String note,String actor){var target=versions.findById(targetId).orElseThrow(()->AppException.notFound("目标版本不存在"));if(!target.channelId.equals(channelId))throw AppException.conflict("版本不属于该渠道");var body=(ObjectNode)target.payload.deepCopy();body.put("sourceHash","rollback:"+target.id+":"+System.nanoTime());body.put("fileName","回滚自V"+target.versionNumber+" · "+body.path("fileName").asText("历史版本"));body.put("rollbackFromVersionId",target.id.toString());var draft=(ObjectNode)createDraft(channelId,body);var id=UUID.fromString(draft.path("id").asText());return publish(channelId,id,note==null||note.isBlank()?"回滚至V"+target.versionNumber:note,actor);}
    private JsonNode providerView(LogisticsProviderEntity row){var body=(ObjectNode)row.payload.deepCopy();body.put("_version",row.version);return body;}
    private JsonNode channelView(LogisticsChannelEntity row){var body=(ObjectNode)row.payload.deepCopy();body.put("currentVersionId",row.currentVersionId==null?"":row.currentVersionId.toString());body.put("_version",row.version);return body;}
    private JsonNode versionView(LogisticsVersionEntity row){var body=(ObjectNode)row.payload.deepCopy();body.put("id",row.id.toString());body.put("channelId",row.channelId.toString());body.put("versionNumber",row.versionNumber);body.put("status",row.status);return body;}
    private static String required(ObjectNode body,String key,int max){var value=body.path(key).asText("").trim();if(value.isEmpty()||value.length()>max)throw AppException.unprocessable(key+"不能为空或过长");return value;}
    private static UUID uuid(String value,String message){try{return UUID.fromString(value);}catch(Exception e){throw AppException.unprocessable(message);}}
    public record Workspace(List<JsonNode> providers,List<JsonNode> channels,List<JsonNode> versions){}
}
