package com.milano.quotation.logistics;

import tools.jackson.databind.node.ObjectNode;
import com.milano.quotation.audit.AuditService;
import com.milano.quotation.common.ApiResponse;
import com.milano.quotation.common.PageResponse;
import com.milano.quotation.idempotency.IdempotencyService;
import com.milano.quotation.security.QuotationPrincipal;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.databind.JsonNode;
import java.util.List;import java.util.Map;import java.util.UUID;

@RestController @RequestMapping("/api/v1/logistics") @PreAuthorize("hasAuthority('PERM_logistics')") @Transactional
public class LogisticsController{
    private final LogisticsService logistics;private final LogisticsQueryService queries;private final LogisticsWorkbookService workbooks;private final AuditService audit;private final IdempotencyService idempotency;public LogisticsController(LogisticsService logistics,LogisticsQueryService queries,LogisticsWorkbookService workbooks,AuditService audit,IdempotencyService idempotency){this.logistics=logistics;this.queries=queries;this.workbooks=workbooks;this.audit=audit;this.idempotency=idempotency;}
    @GetMapping("/workspace")ApiResponse<LogisticsService.Workspace>workspace(){return ApiResponse.ok(logistics.workspace());}
    @GetMapping("/providers")ApiResponse<PageResponse<JsonNode>>providers(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size,@RequestParam(defaultValue="")String query,@RequestParam(required=false)Boolean enabled){return ApiResponse.ok(queries.providers(page,size,query,enabled));}
    @GetMapping("/channels")ApiResponse<PageResponse<JsonNode>>channels(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size,@RequestParam(defaultValue="")String query,@RequestParam(required=false)UUID providerId,@RequestParam(required=false)Boolean enabled,@RequestParam(defaultValue="false")Boolean archived){return ApiResponse.ok(queries.channels(page,size,query,providerId,enabled,archived));}
    @GetMapping("/versions")ApiResponse<PageResponse<JsonNode>>versions(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size,@RequestParam(required=false)UUID channelId,@RequestParam(defaultValue="")String status){return ApiResponse.ok(queries.versions(page,size,channelId,status));}
    @GetMapping("/versions/{versionId}/rows")ApiResponse<PageResponse<JsonNode>>versionRows(@PathVariable UUID versionId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size,@RequestParam(defaultValue="")String countryCode,@RequestParam(defaultValue="")String query){return ApiResponse.ok(queries.versionRows(versionId,page,size,countryCode,query));}
    @GetMapping("/versions/{versionId}/issues")ApiResponse<PageResponse<JsonNode>>versionIssues(@PathVariable UUID versionId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size){return ApiResponse.ok(queries.versionIssues(versionId,page,size));}
    @GetMapping("/versions/{versionId}/diff")ApiResponse<PageResponse<JsonNode>>versionDiff(@PathVariable UUID versionId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="100")int size){return ApiResponse.ok(queries.versionDiff(versionId,page,size));}
    @PostMapping("/providers")ApiResponse<?>provider(@RequestBody ObjectNode body,@RequestHeader("Idempotency-Key")String key,Authentication auth){var existing=idempotency.existing(account(auth),"logistics-provider-create",key,body);if(existing.isPresent())return ApiResponse.ok(existing.get());var result=logistics.addProvider(body);idempotency.save(account(auth),"logistics-provider-create",key,body,result);audit.record("logistics.provider-create","logistics-provider",result.path("id").asText(),"success",Map.of());return ApiResponse.ok(result);}
    @PatchMapping("/providers/{providerId}/status")ApiResponse<?>providerStatus(@PathVariable UUID providerId,@RequestBody ObjectNode body,@RequestHeader("If-Match")long version,Authentication auth){var result=logistics.setProviderEnabled(providerId,body.path("enabled").asBoolean(),version);audit.record("logistics.provider-status","logistics-provider",providerId.toString(),"success",Map.of("enabled",body.path("enabled").asBoolean(),"actor",account(auth)));return ApiResponse.ok(result);}
    @DeleteMapping("/providers/{providerId}")ApiResponse<Void>deleteProvider(@PathVariable UUID providerId,Authentication auth){logistics.deleteProvider(providerId);audit.record("logistics.provider-delete","logistics-provider",providerId.toString(),"success",Map.of("actor",account(auth)));return ApiResponse.ok(null);}
    @PostMapping("/channels")ApiResponse<?>channel(@RequestBody ObjectNode body,@RequestHeader("Idempotency-Key")String key,Authentication auth){var existing=idempotency.existing(account(auth),"logistics-channel-create",key,body);if(existing.isPresent())return ApiResponse.ok(existing.get());var result=logistics.addChannel(body);idempotency.save(account(auth),"logistics-channel-create",key,body,result);audit.record("logistics.channel-create","logistics-channel",result.path("id").asText(),"success",Map.of());return ApiResponse.ok(result);}
    @PutMapping("/channels/{channelId}")ApiResponse<?>updateChannel(@PathVariable UUID channelId,@RequestBody ObjectNode body,@RequestHeader("If-Match")long version,Authentication auth){var result=logistics.updateChannel(channelId,body,version);audit.record("logistics.channel-update","logistics-channel",channelId.toString(),"success",Map.of("actor",account(auth)));return ApiResponse.ok(result);}
    @PatchMapping("/channels/{channelId}/status")ApiResponse<?>channelStatus(@PathVariable UUID channelId,@RequestBody ObjectNode body,@RequestHeader("If-Match")long version,Authentication auth){var result=logistics.setChannelEnabled(channelId,body.path("enabled").asBoolean(),version);audit.record("logistics.channel-status","logistics-channel",channelId.toString(),"success",Map.of("enabled",body.path("enabled").asBoolean(),"actor",account(auth)));return ApiResponse.ok(result);}
    @PostMapping("/channels/{channelId}/clone")ApiResponse<?>cloneChannel(@PathVariable UUID channelId,@RequestBody ObjectNode body,@RequestHeader("Idempotency-Key")String key,Authentication auth){body.put("sourceChannelId",channelId.toString());var existing=idempotency.existing(account(auth),"logistics-channel-clone",key,body);if(existing.isPresent())return ApiResponse.ok(existing.get());var result=logistics.cloneChannel(channelId,body);idempotency.save(account(auth),"logistics-channel-clone",key,body,result);audit.record("logistics.channel-clone","logistics-channel",result.path("id").asText(),"success",Map.of("sourceChannelId",channelId));return ApiResponse.ok(result);}
    @DeleteMapping("/channels/{channelId}")ApiResponse<Void>deleteChannel(@PathVariable UUID channelId,Authentication auth){logistics.deleteChannel(channelId);audit.record("logistics.channel-delete","logistics-channel",channelId.toString(),"success",Map.of("actor",account(auth)));return ApiResponse.ok(null);}
    @PostMapping("/channels/{channelId}/archive")ApiResponse<?>archiveChannel(@PathVariable UUID channelId,@RequestBody ObjectNode body,@RequestHeader("If-Match")long version,@RequestHeader("Idempotency-Key")String key,Authentication auth){body.put("channelId",channelId.toString()).put("expectedVersion",version);var actor=account(auth);var existing=idempotency.existing(actor,"logistics-channel-archive",key,body);if(existing.isPresent())return ApiResponse.ok(existing.get());var result=logistics.archiveChannel(channelId,body.path("reason").asText(),actor,version);idempotency.save(actor,"logistics-channel-archive",key,body,result);audit.record("logistics.channel-archive","logistics-channel",channelId.toString(),"success",Map.of("actor",actor,"reason",body.path("reason").asText(),"rejectedDrafts",result.path("rejectedDrafts").asInt()));for(var rejected:result.path("rejectedVersionIds"))audit.record("logistics.draft-terminate","logistics-version",rejected.asText(),"success",Map.of("actor",actor,"channelId",channelId,"reason","channel-archive"));return ApiResponse.ok(result);}
    @PutMapping("/channels/{channelId}/manual-draft")ApiResponse<?>manualDraft(@PathVariable UUID channelId,@RequestBody ObjectNode body,@RequestHeader("Idempotency-Key")String key,Authentication auth){body.put("actor",account(auth));var existing=idempotency.existing(account(auth),"logistics-manual-draft",key,body);if(existing.isPresent())return ApiResponse.ok(existing.get());var result=logistics.createManualDraft(channelId,body);idempotency.save(account(auth),"logistics-manual-draft",key,body,result);audit.record("logistics.manual-draft","logistics-version",result.path("id").asText(),"success",Map.of("channelId",channelId,"rows",body.path("rows").size()));return ApiResponse.ok(result);}
    @PostMapping("/channels/{channelId}/versions")ApiResponse<?>draft(@PathVariable UUID channelId,@RequestBody ObjectNode body,@RequestHeader("Idempotency-Key")String key,Authentication auth){body.put("channelId",channelId.toString());var existing=idempotency.existing(account(auth),"logistics-version-create",key,body);if(existing.isPresent())return ApiResponse.ok(existing.get());var result=logistics.createDraft(channelId,body);idempotency.save(account(auth),"logistics-version-create",key,body,result);audit.record("logistics.import","logistics-version",result.path("id").asText(),"success",Map.of());return ApiResponse.ok(result);}
    @PostMapping(value="/channels/{channelId}/imports",consumes="multipart/form-data")ApiResponse<?>importWorkbook(@PathVariable UUID channelId,@RequestPart("file")MultipartFile file,@RequestParam(defaultValue="false")boolean replaceDraft,@RequestHeader("Idempotency-Key")String key,Authentication auth){var parsed=workbooks.parse(file,logistics.publishedRows(channelId));parsed.put("channelId",channelId.toString());parsed.put("importedBy",account(auth));parsed.put("publishedBy","");parsed.put("auditNote","");parsed.put("replaceDraft",replaceDraft);var existing=idempotency.existing(account(auth),"logistics-workbook-import",key,parsed);if(existing.isPresent())return ApiResponse.ok(existing.get());var result=replaceDraft?logistics.createDraftReplacing(channelId,parsed,"被新上传的价格草稿终止"):logistics.createDraft(channelId,parsed);idempotency.save(account(auth),"logistics-workbook-import",key,parsed,result);audit.record("logistics.import","logistics-version",result.path("id").asText(),"success",Map.of("file",file.getOriginalFilename(),"rows",parsed.path("validRows").asInt()));return ApiResponse.ok(result);}
    @PostMapping(value="/providers/{providerId}/imports/preview",consumes="multipart/form-data")ApiResponse<?>previewProviderImports(@PathVariable UUID providerId,@RequestPart(value="files",required=false)List<MultipartFile> files){return ApiResponse.ok(previewBatch(providerId,files));}
    @PostMapping(value="/providers/{providerId}/imports",consumes="multipart/form-data")ApiResponse<?>importProviderFiles(@PathVariable UUID providerId,@RequestPart(value="files",required=false)List<MultipartFile> files,@RequestParam(defaultValue="false")boolean replaceDrafts,@RequestHeader("Idempotency-Key")String key,Authentication auth){var actor=account(auth);var stableRequest=batchIdempotencyRequest(providerId,files,replaceDrafts);var existing=idempotency.existing(actor,"logistics-provider-batch-import",key,stableRequest);if(existing.isPresent())return ApiResponse.ok(existing.get());var request=previewBatch(providerId,files);request.put("replaceDrafts",replaceDrafts);var result=logistics.importProviderBatch(providerId,(tools.jackson.databind.node.ArrayNode)request.path("items"),actor,replaceDrafts);idempotency.save(actor,"logistics-provider-batch-import",key,stableRequest,result);for(var item:result.path("items")){var action=item.path("action").asText();audit.record(action.startsWith("restored")?"logistics.channel-restore":"logistics.batch-import","logistics-version",item.path("versionId").asText(),"success",Map.of("providerId",providerId,"channelId",item.path("channelId").asText(),"file",item.path("fileName").asText(),"action",action));}return ApiResponse.ok(result);}
    @PostMapping(value="/imports/preview",consumes="multipart/form-data")ApiResponse<?>previewGlobalImports(@RequestPart(value="files",required=false)List<MultipartFile> files){return ApiResponse.ok(previewBatch(null,files));}
    @PostMapping(value="/imports",consumes="multipart/form-data")ApiResponse<?>importGlobalFiles(@RequestPart(value="files",required=false)List<MultipartFile> files,@RequestParam(defaultValue="false")boolean replaceDrafts,@RequestHeader("Idempotency-Key")String key,Authentication auth){var actor=account(auth);var stableRequest=batchIdempotencyRequest(null,files,replaceDrafts);var existing=idempotency.existing(actor,"logistics-global-batch-import",key,stableRequest);if(existing.isPresent())return ApiResponse.ok(existing.get());var request=previewBatch(null,files);request.put("replaceDrafts",replaceDrafts);if(request.path("blocking").asInt()>0)throw com.milano.quotation.common.AppException.unprocessable("所选文件状态已变化，请重新预检");var result=logistics.importGlobalBatch((tools.jackson.databind.node.ArrayNode)request.path("items"),actor,replaceDrafts);idempotency.save(actor,"logistics-global-batch-import",key,stableRequest,result);for(var item:result.path("items")){var action=item.path("action").asText();audit.record(action.startsWith("restored")?"logistics.channel-restore":"logistics.batch-import","logistics-version",item.path("versionId").asText(),"success",Map.of("channelId",item.path("channelId").asText(),"file",item.path("fileName").asText(),"action",action));}return ApiResponse.ok(result);}
    @PostMapping("/providers/{providerId}/versions/publish-batch")ApiResponse<?>publishProviderVersions(@PathVariable UUID providerId,@RequestBody ObjectNode body,@RequestHeader("Idempotency-Key")String key,Authentication auth){body.put("providerId",providerId.toString());var existing=idempotency.existing(account(auth),"logistics-provider-batch-publish",key,body);if(existing.isPresent())return ApiResponse.ok(existing.get());var result=logistics.publishProviderBatch(providerId,(tools.jackson.databind.node.ArrayNode)body.withArray("selections"),body.path("note").asText(),account(auth));idempotency.save(account(auth),"logistics-provider-batch-publish",key,body,result);for(var version:result.path("published"))audit.record("logistics.batch-publish","logistics-version",version.path("id").asText(),"success",Map.of("providerId",providerId,"channelId",version.path("channelId").asText()));return ApiResponse.ok(result);}
    @PostMapping("/channels/{channelId}/versions/{versionId}/reject")ApiResponse<?>rejectVersion(@PathVariable UUID channelId,@PathVariable UUID versionId,@RequestBody ObjectNode body,@RequestHeader("Idempotency-Key")String key,Authentication auth){body.put("channelId",channelId.toString()).put("versionId",versionId.toString());var existing=idempotency.existing(account(auth),"logistics-version-reject",key,body);if(existing.isPresent())return ApiResponse.ok(existing.get());var result=logistics.rejectDraft(channelId,versionId,body.path("note").asText(),account(auth));idempotency.save(account(auth),"logistics-version-reject",key,body,result);audit.record("logistics.reject","logistics-version",versionId.toString(),"success",Map.of("channelId",channelId,"note",body.path("note").asText()));return ApiResponse.ok(result);}
    @PostMapping("/channels/{channelId}/versions/{versionId}/publish")ApiResponse<?>publish(@PathVariable UUID channelId,@PathVariable UUID versionId,@RequestBody(required=false)ObjectNode body,@RequestHeader("Idempotency-Key")String key,Authentication auth){var request=body==null?tools.jackson.databind.node.JsonNodeFactory.instance.objectNode():body;request.put("channelId",channelId.toString()).put("versionId",versionId.toString());var existing=idempotency.existing(account(auth),"logistics-publish",key,request);if(existing.isPresent())return ApiResponse.ok(existing.get());var note=request.path("note").asText("");var result=logistics.publish(channelId,versionId,note,account(auth),request.path("removalConfirmed").asBoolean(false));idempotency.save(account(auth),"logistics-publish",key,request,result);audit.record("logistics.publish","logistics-version",versionId.toString(),"success",Map.of("channelId",channelId));return ApiResponse.ok(result);}
    @PostMapping("/channels/{channelId}/versions/{versionId}/rollback")ApiResponse<?>rollback(@PathVariable UUID channelId,@PathVariable UUID versionId,@RequestBody(required=false)ObjectNode body,@RequestHeader("Idempotency-Key")String key,Authentication auth){var request=body==null?tools.jackson.databind.node.JsonNodeFactory.instance.objectNode():body;request.put("channelId",channelId.toString()).put("versionId",versionId.toString());var existing=idempotency.existing(account(auth),"logistics-rollback",key,request);if(existing.isPresent())return ApiResponse.ok(existing.get());var note=request.path("note").asText("");var result=logistics.rollback(channelId,versionId,note,account(auth));idempotency.save(account(auth),"logistics-rollback",key,request,result);audit.record("logistics.rollback","logistics-version",result.path("id").asText(),"success",Map.of("channelId",channelId,"targetVersionId",versionId));return ApiResponse.ok(result);}
    private ObjectNode previewBatch(UUID fixedProviderId,List<MultipartFile> files){validateFiles(files);var result=tools.jackson.databind.node.JsonNodeFactory.instance.objectNode();if(fixedProviderId!=null)result.put("providerId",fixedProviderId.toString());var items=result.putArray("items");var claimed=new java.util.HashMap<String,ObjectNode>();for(int index=0;index<files.size();index++){var file=files.get(index);ObjectNode parsed;ObjectNode providerMatch=null;UUID matchedProviderId=null;try{providerMatch=fixedProviderId==null?logistics.matchGlobalProvider(file.getOriginalFilename()):tools.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("providerMatchStatus","matched").put("providerId",fixedProviderId.toString());if(!"matched".equals(providerMatch.path("providerMatchStatus").asText())){parsed=blocked(file,index,providerMatch.path("providerMatchMessage").asText("物流商匹配失败"));parsed.setAll(providerMatch);items.add(parsed);continue;}matchedProviderId=UUID.fromString(providerMatch.path("providerId").asText());var initial=workbooks.parse(file,tools.jackson.databind.node.JsonNodeFactory.instance.arrayNode());var match=logistics.matchProviderFile(matchedProviderId,initial.path("fileName").asText(),initial.path("sourceHash").asText());var channelId=match.path("channelId").asText();parsed=channelId.isBlank()?initial:workbooks.parse(file,logistics.publishedRows(UUID.fromString(channelId)));parsed.setAll(providerMatch);parsed.setAll(match);parsed.put("fileIndex",index).put("fileKey",index+":"+parsed.path("sourceHash").asText());var claim=matchedProviderId+":"+(channelId.isBlank()?match.path("channelCode").asText():channelId);if(claimed.containsKey(claim)){addIssue(parsed,0,"文件","同一批次中一个渠道只能对应一个文件");addIssue(claimed.get(claim),0,"文件","同一批次中一个渠道只能对应一个文件");}else claimed.put(claim,parsed);}catch(RuntimeException exception){parsed=blocked(file,index,exception.getMessage());if(providerMatch!=null)parsed.setAll(providerMatch);if(matchedProviderId!=null)try{var fallbackMatch=logistics.matchProviderFile(matchedProviderId,file.getOriginalFilename(),parsed.path("sourceHash").asText());if(fallbackMatch!=null)parsed.setAll(fallbackMatch);}catch(RuntimeException matchError){addIssue(parsed,0,"渠道匹配",matchError.getMessage());}}items.add(parsed);}var blocking=java.util.stream.StreamSupport.stream(items.spliterator(),false).mapToInt(item->item.path("errors").asInt()>0?1:0).sum();var replace=java.util.stream.StreamSupport.stream(items.spliterator(),false).filter(item->item.path("errors").asInt()==0&&item.path("hasDraft").asBoolean()).count();result.put("count",items.size()).put("blocking",blocking).put("selectable",items.size()-blocking).put("replaceDrafts",replace);return result;}
    private static void validateFiles(List<MultipartFile> files){if(files==null||files.isEmpty())throw com.milano.quotation.common.AppException.unprocessable("请选择至少一个物流模板");if(files.size()>100)throw com.milano.quotation.common.AppException.unprocessable("单次最多导入100个物流模板");long total=0;for(var file:files){if(file.getSize()>100L*1024*1024)throw com.milano.quotation.common.AppException.unprocessable("单个文件不能超过100MB："+file.getOriginalFilename());total+=file.getSize();}if(total>500L*1024*1024)throw com.milano.quotation.common.AppException.unprocessable("单批文件总大小不能超过500MB");}
    private static ObjectNode blocked(MultipartFile file,int index,String message){var hash=fileHash(file);var item=tools.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("fileIndex",index).put("fileKey",index+":"+hash).put("fileName",file.getOriginalFilename()).put("sourceHash",hash).put("action","blocked").put("validRows",0).put("errors",1).put("warnings",0).put("hasDraft",false);item.putObject("summary").put("added",0).put("price",0).put("rule",0).put("removed",0).put("unchanged",0).put("highRisk",0);item.putArray("diffRows");item.putArray("issues").addObject().put("row",0).put("field","文件").put("message",message==null?"文件预检失败":message).put("level","error");return item;}
    private static String fileHash(MultipartFile file){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(file.getBytes()));}catch(Exception exception){return "unreadable-"+file.getSize();}}
    private static ObjectNode batchIdempotencyRequest(UUID providerId,List<MultipartFile> files,boolean replaceDrafts){validateFiles(files);var request=tools.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("replaceDrafts",replaceDrafts);if(providerId!=null)request.put("providerId",providerId.toString());var identities=request.putArray("files");for(int index=0;index<files.size();index++){var file=files.get(index);identities.addObject().put("index",index).put("fileName",file.getOriginalFilename()).put("size",file.getSize()).put("sourceHash",fileHash(file));}return request;}
    private static void addIssue(ObjectNode item,int row,String field,String message){item.withArray("issues").addObject().put("row",row).put("field",field).put("message",message).put("level","error");item.put("errors",item.path("errors").asInt()+1).put("action","blocked");}
    private static String account(Authentication auth){return ((QuotationPrincipal)auth.getPrincipal()).account();}
}
