package com.milano.quotation.logistics;

import tools.jackson.databind.JsonNode;
import tools.jackson.databind.node.ArrayNode;
import tools.jackson.databind.node.ObjectNode;
import com.milano.quotation.common.AppException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant;import java.util.*;

@Service
public class LogisticsService{
    private final LogisticsProviderRepository providers;private final LogisticsChannelRepository channels;private final LogisticsVersionRepository versions;
    public LogisticsService(LogisticsProviderRepository providers,LogisticsChannelRepository channels,LogisticsVersionRepository versions){this.providers=providers;this.channels=channels;this.versions=versions;}
    @Transactional(readOnly=true) public long publishedChannelCount(){return channels.countByCurrentVersionIdIsNotNull();}
    @Transactional(readOnly=true) public ArrayNode publishedRows(UUID channelId){var channel=channels.findById(channelId).orElseThrow(()->AppException.notFound("物流渠道不存在"));if(channel.currentVersionId==null)return tools.jackson.databind.node.JsonNodeFactory.instance.arrayNode();var version=versions.findById(channel.currentVersionId).orElseThrow(()->AppException.notFound("物流正式版本不存在"));var rows=version.payload.path("rows");return rows.isArray()?(ArrayNode)rows.deepCopy():tools.jackson.databind.node.JsonNodeFactory.instance.arrayNode();}
    @Transactional(readOnly=true) public Workspace workspace(){return new Workspace(providers.findAllByOrderByUpdatedAtDesc().stream().map(this::providerView).toList(),channels.findAllByOrderByUpdatedAtDesc().stream().map(this::channelView).toList(),versions.findAllByOrderByCreatedAtDesc().stream().map(this::versionView).toList());}
    @Transactional public JsonNode addProvider(ObjectNode body){var name=required(body,"name",120);var code=required(body,"code",64).toUpperCase(Locale.ROOT);if(providers.existsByCodeIgnoreCase(code))throw AppException.conflict("物流商编码已存在");var now=Instant.now();var row=new LogisticsProviderEntity();row.id=UUID.randomUUID();row.code=code;var payload=body.deepCopy();payload.put("id",row.id.toString());payload.put("name",name);payload.put("code",code);payload.put("enabled",body.path("enabled").asBoolean(true));payload.put("createdAt",now.toString());payload.put("updatedAt",now.toString());row.payload=payload;row.createdAt=now;row.updatedAt=now;providers.save(row);return providerView(row);}
    @Transactional public JsonNode addChannel(ObjectNode body){var providerId=uuid(body.path("providerId").asText(),"物流商不存在");if(!providers.existsById(providerId))throw AppException.notFound("物流商不存在");var name=required(body,"name",120);var code=required(body,"code",96).toUpperCase(Locale.ROOT);if(channels.existsByCodeIgnoreCase(code))throw AppException.conflict("渠道编码已存在");var now=Instant.now();var row=new LogisticsChannelEntity();row.id=UUID.randomUUID();row.providerId=providerId;row.code=code;row.ruleId=channels.findAll().stream().mapToInt(item->item.ruleId).max().orElse(0)+1;var payload=body.deepCopy();payload.put("id",row.id.toString());payload.put("ruleId",row.ruleId);payload.put("providerId",providerId.toString());payload.put("name",name);payload.put("code",code);payload.put("enabled",body.path("enabled").asBoolean(true));payload.put("currentVersionId","");payload.put("createdAt",now.toString());payload.put("updatedAt",now.toString());row.payload=payload;row.createdAt=now;row.updatedAt=now;channels.save(row);return channelView(row);}
    @Transactional public JsonNode updateChannel(UUID id,ObjectNode body,long expectedVersion){var row=channels.findById(id).orElseThrow(()->AppException.notFound("物流渠道不存在"));if(row.version!=expectedVersion)throw AppException.conflict("物流渠道已被其他用户修改，请刷新后重试");var code=required(body,"code",96).toUpperCase(Locale.ROOT);if(!row.code.equalsIgnoreCase(code)&&channels.existsByCodeIgnoreCase(code))throw AppException.conflict("渠道编码已存在");var payload=(ObjectNode)row.payload;payload.put("name",required(body,"name",120));payload.put("code",code);payload.put("type",body.path("type").asText("专线"));payload.put("logisticsAttribute",body.path("logisticsAttribute").asText("普货"));payload.put("enabled",body.path("enabled").asBoolean(payload.path("enabled").asBoolean(true)));payload.put("updatedAt",Instant.now().toString());row.code=code;row.updatedAt=Instant.now();channels.saveAndFlush(row);return channelView(row);}
    @Transactional public JsonNode setChannelEnabled(UUID id,boolean enabled,long expectedVersion){var row=channels.findById(id).orElseThrow(()->AppException.notFound("物流渠道不存在"));if(row.version!=expectedVersion)throw AppException.conflict("物流渠道已被其他用户修改，请刷新后重试");((ObjectNode)row.payload).put("enabled",enabled).put("updatedAt",Instant.now().toString());row.updatedAt=Instant.now();channels.saveAndFlush(row);return channelView(row);}
    @Transactional public JsonNode cloneChannel(UUID id,ObjectNode body){var source=channels.findById(id).orElseThrow(()->AppException.notFound("物流渠道不存在"));var input=(ObjectNode)source.payload.deepCopy();input.put("name",body.path("name").asText(input.path("name").asText()+"-副本"));input.put("code",required(body,"code",96));input.put("providerId",source.providerId.toString());input.put("currentVersionId","");var clone=addChannel(input);if(source.currentVersionId!=null){var published=versions.findById(source.currentVersionId).orElseThrow(()->AppException.notFound("物流正式版本不存在"));var draftBody=(ObjectNode)published.payload.deepCopy();draftBody.put("sourceHash","clone:"+source.id+":"+UUID.randomUUID());draftBody.put("fileName","克隆自"+published.payload.path("fileName").asText("正式版本"));draftBody.put("auditNote","克隆渠道产生的待审草稿");createDraft(UUID.fromString(clone.path("id").asText()),draftBody);}return clone;}
    @Transactional public void deleteChannel(UUID id){var row=channels.findById(id).orElseThrow(()->AppException.notFound("物流渠道不存在"));if(!versions.findByChannelIdOrderByVersionNumberDesc(id).isEmpty())throw AppException.conflict("渠道已有版本记录，只能停用，不能删除");channels.delete(row);}
    @Transactional public JsonNode createManualDraft(UUID channelId,ObjectNode body){var rows=body.path("rows");if(!rows.isArray())throw AppException.unprocessable("区域规则必须是数组");for(var row:rows){var from=row.path("weightFromKg").asDouble(-1);var to=row.path("weightToKg").asDouble(-1);if(from<0||to<from)throw AppException.unprocessable("区域计费重量范围非法");if(row.path("areaName").asText("").isBlank())throw AppException.unprocessable("区域名称不能为空");}versions.findByChannelIdOrderByVersionNumberDesc(channelId).stream().filter(version->"draft".equals(version.status)).forEach(version->{version.status="rejected";((ObjectNode)version.payload).put("status","rejected").put("auditNote","被后续手工编辑草稿替代");});var payload=tools.jackson.databind.node.JsonNodeFactory.instance.objectNode();payload.put("sourceHash","manual:"+channelId+":"+UUID.randomUUID());payload.put("fileName",body.path("fileName").asText("手工维护区域规则"));payload.set("rows",rows.deepCopy());payload.set("issues",tools.jackson.databind.node.JsonNodeFactory.instance.arrayNode());payload.set("diffRows",tools.jackson.databind.node.JsonNodeFactory.instance.arrayNode());payload.set("summary",tools.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("added",rows.size()).put("price",0).put("rule",0).put("removed",0).put("unchanged",0).put("highRisk",0));payload.put("validRows",rows.size()).put("errors",0).put("warnings",0).put("importedBy",body.path("actor").asText("物流负责人")).put("publishedBy","").put("auditNote",body.path("note").asText("手工维护产生的待审草稿"));return createDraft(channelId,payload);}
    @Transactional public JsonNode createDraft(UUID channelId,ObjectNode body){var channel=channels.findById(channelId).orElseThrow(()->AppException.notFound("物流渠道不存在"));var sourceHash=required(body,"sourceHash",128);var duplicate=versions.findByChannelIdAndSourceHash(channelId,sourceHash);if(duplicate.isPresent())return versionView(duplicate.get());var now=Instant.now();var row=new LogisticsVersionEntity();row.id=UUID.randomUUID();row.channelId=channelId;row.versionNumber=versions.findByChannelIdOrderByVersionNumberDesc(channelId).stream().mapToInt(v->v.versionNumber).max().orElse(0)+1;row.status="draft";row.sourceHash=sourceHash;var payload=body.deepCopy();payload.put("id",row.id.toString());payload.put("channelId",channelId.toString());payload.put("versionNumber",row.versionNumber);payload.put("status","draft");payload.put("importedAt",now.toString());payload.put("publishedAt","");row.payload=payload;row.createdAt=now;versions.save(row);return versionView(row);}
    @Transactional public JsonNode publish(UUID channelId,UUID versionId,String note,String actor,boolean removalConfirmed){var channel=channels.findById(channelId).orElseThrow(()->AppException.notFound("物流渠道不存在"));var target=versions.findById(versionId).orElseThrow(()->AppException.notFound("物流版本不存在"));if(!target.channelId.equals(channelId))throw AppException.conflict("版本不属于该渠道");if(!"draft".equals(target.status))throw AppException.conflict("只有待审核草稿可以发布");if(note==null||note.isBlank())throw AppException.unprocessable("发布审核备注不能为空");if(target.payload.path("errors").asInt()>0)throw AppException.unprocessable("当前版本存在阻断错误，禁止发布");if(target.payload.path("summary").path("removed").asInt()>0&&!removalConfirmed)throw AppException.unprocessable("存在移除项时必须明确确认");var now=Instant.now();versions.findByChannelIdOrderByVersionNumberDesc(channelId).stream().filter(v->v.status.equals("published")).forEach(v->{v.status="superseded";((ObjectNode)v.payload).put("status","superseded");});target.status="published";target.publishedAt=now;var payload=(ObjectNode)target.payload;payload.put("status","published");payload.put("publishedAt",now.toString());payload.put("publishedBy",actor);payload.put("auditNote",note.trim());channel.currentVersionId=target.id;channel.updatedAt=now;var channelPayload=(ObjectNode)channel.payload;channelPayload.put("currentVersionId",target.id.toString());channelPayload.put("updatedAt",now.toString());return versionView(target);}
    @Transactional public JsonNode rollback(UUID channelId,UUID targetId,String note,String actor){var target=versions.findById(targetId).orElseThrow(()->AppException.notFound("目标版本不存在"));if(!target.channelId.equals(channelId))throw AppException.conflict("版本不属于该渠道");var body=(ObjectNode)target.payload.deepCopy();body.put("sourceHash","rollback:"+target.id+":"+System.nanoTime());body.put("fileName","回滚自V"+target.versionNumber+" · "+body.path("fileName").asText("历史版本"));body.put("rollbackFromVersionId",target.id.toString());var draft=(ObjectNode)createDraft(channelId,body);var id=UUID.fromString(draft.path("id").asText());return publish(channelId,id,note==null||note.isBlank()?"回滚至V"+target.versionNumber:note,actor,true);}
    @Transactional public ObjectNode importMigrationDrafts(ArrayNode entries,String actor){
        var result=tools.jackson.databind.node.JsonNodeFactory.instance.objectNode();var createdProviders=result.putArray("createdProviders");var createdChannels=result.putArray("createdChannels");var createdVersions=result.putArray("createdVersions");int importedRows=0;
        for(var entry:entries){var value=entry.path("value");var providerCode=required((ObjectNode)value,"providerCode",64).toUpperCase(Locale.ROOT);var provider=providers.findByCodeIgnoreCase(providerCode).orElse(null);
            if(provider==null){var providerBody=tools.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("name",value.path("providerName").asText()).put("code",providerCode).put("enabled",true);var view=addProvider(providerBody);provider=providers.findById(UUID.fromString(view.path("id").asText())).orElseThrow();createdProviders.add(provider.id.toString());}
            var channelCode=required((ObjectNode)value,"channelCode",96).toUpperCase(Locale.ROOT);var channel=channels.findByCodeIgnoreCase(channelCode).orElse(null);
            if(channel==null){var channelBody=tools.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("providerId",provider.id.toString()).put("name",value.path("channelName").asText()).put("code",channelCode).put("type","专线").put("logisticsAttribute","普货").put("enabled",true);var view=addChannel(channelBody);channel=channels.findById(UUID.fromString(view.path("id").asText())).orElseThrow();createdChannels.add(channel.id.toString());}
            var sourceHash=value.path("sourceHash").asText();var duplicate=versions.findByChannelIdAndSourceHash(channel.id,sourceHash);if(duplicate.isPresent())continue;
            var rows=value.path("rows");if(!rows.isArray()||rows.isEmpty())throw AppException.unprocessable("物流迁移条目没有有效价格段："+value.path("fileName").asText());
            var body=tools.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("sourceHash",sourceHash).put("fileName",value.path("fileName").asText()).put("importedBy",actor).put("publishedBy","").put("auditNote","真实数据迁移产生的待审核草稿");
            body.set("rows",rows.deepCopy());body.set("issues",value.path("issues").deepCopy());body.set("summary",value.path("summary").deepCopy());body.put("validRows",rows.size()).put("errors",value.path("errors").asInt()).put("warnings",value.path("warnings").asInt());
            var draft=createDraft(channel.id,body);createdVersions.add(draft.path("id").asText());importedRows+=rows.size();}
        result.put("providersCreated",createdProviders.size()).put("channelsCreated",createdChannels.size()).put("versionsCreated",createdVersions.size()).put("priceRowsImported",importedRows);return result;
    }
    @Transactional public ObjectNode rollbackMigration(JsonNode execution){var removedVersions=0;var removedChannels=0;var removedProviders=0;var logistics=execution.path("logistics");
        for(var value:logistics.path("createdVersions")){try{var id=UUID.fromString(value.asText());var row=versions.findById(id).orElse(null);if(row!=null){if(!"draft".equals(row.status))throw AppException.conflict("已发布物流版本不能由迁移回滚删除");versions.delete(row);removedVersions++;}}catch(IllegalArgumentException ignored){}}
        versions.flush();for(var value:logistics.path("createdChannels")){try{var id=UUID.fromString(value.asText());if(versions.findByChannelIdOrderByVersionNumberDesc(id).isEmpty()&&channels.existsById(id)){channels.deleteById(id);removedChannels++;}}catch(IllegalArgumentException ignored){}}
        channels.flush();for(var value:logistics.path("createdProviders")){try{var id=UUID.fromString(value.asText());if(channels.countByProviderId(id)==0&&providers.existsById(id)){providers.deleteById(id);removedProviders++;}}catch(IllegalArgumentException ignored){}}
        return tools.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("versionsRemoved",removedVersions).put("channelsRemoved",removedChannels).put("providersRemoved",removedProviders);}
    private JsonNode providerView(LogisticsProviderEntity row){var body=(ObjectNode)row.payload.deepCopy();body.put("_version",row.version);return body;}
    private JsonNode channelView(LogisticsChannelEntity row){var body=(ObjectNode)row.payload.deepCopy();body.put("currentVersionId",row.currentVersionId==null?"":row.currentVersionId.toString());body.put("_version",row.version);return body;}
    private JsonNode versionView(LogisticsVersionEntity row){var body=(ObjectNode)row.payload.deepCopy();body.put("id",row.id.toString());body.put("channelId",row.channelId.toString());body.put("versionNumber",row.versionNumber);body.put("status",row.status);return body;}
    private static String required(ObjectNode body,String key,int max){var value=body.path(key).asText("").trim();if(value.isEmpty()||value.length()>max)throw AppException.unprocessable(key+"不能为空或过长");return value;}
    private static UUID uuid(String value,String message){try{return UUID.fromString(value);}catch(Exception e){throw AppException.unprocessable(message);}}
    public record Workspace(List<JsonNode> providers,List<JsonNode> channels,List<JsonNode> versions){}
}
