<script setup lang="ts">
import { ref } from 'vue'
import { buildLegacyMigrationExport, downloadMigrationExport } from '@/data/legacyMigrationExport'

const loading = ref(false)
const report = ref<Awaited<ReturnType<typeof buildLegacyMigrationExport>> | null>(null)
const error = ref('')
const sourceOrigin = window.location.origin
async function scan() { loading.value = true; error.value = ''; try { report.value = await buildLegacyMigrationExport() } catch (reason) { error.value = reason instanceof Error ? reason.message : '盘点失败' } finally { loading.value = false } }
</script>

<template><main><section><small>LOCAL SOURCE MIGRATION</small><h1>本地报价数据盘点与白名单导出</h1><p>必须在原来保存数据的同一浏览器、同一地址来源中打开本页。导出不会上传数据，也不会包含账号、密码、Session或默认草稿。</p><div class="warning">来源：{{ sourceOrigin }}。localhost 与 127.0.0.1 属于不同来源，请使用原来实际保存数据的地址。</div><button :disabled="loading" @click="scan">{{ loading ? '正在扫描…' : '开始只读盘点' }}</button><p v-if="error" class="error">{{ error }}</p><template v-if="report"><div class="stats"><article><b>{{ report.totals.entries }}</b><span>数据容器</span></article><article><b>{{ report.totals.migrate }}</b><span>迁移候选</span></article><article><b>{{ report.totals.review }}</b><span>待确认</span></article><article><b>{{ report.totals.exclude }}</b><span>默认排除</span></article><article><b>{{ report.totals.images }}</b><span>图片哈希</span></article></div><table><thead><tr><th>来源</th><th>键 / 数据表</th><th>分类</th><th>数量</th><th>决策</th><th>原因</th></tr></thead><tbody><tr v-for="entry in report.entries" :key="`${entry.source}-${entry.container}-${entry.key}`"><td>{{ entry.source }}</td><td>{{ entry.container }} / {{ entry.key }}</td><td>{{ entry.category }}</td><td>{{ entry.count }}</td><td><em :class="entry.decision">{{ entry.decision }}</em></td><td>{{ entry.reason }}</td></tr></tbody></table><button class="download" @click="downloadMigrationExport(report)">下载JSON白名单报告</button></template></section></main></template>

<style scoped>main{box-sizing:border-box;min-height:100vh;padding:35px;background:#071d2f;font-family:"Microsoft YaHei",sans-serif}section{max-width:1100px;margin:auto;padding:30px;border-radius:14px;background:#fff;color:#172431}small{color:#d87600;font-weight:900;letter-spacing:.16em}h1{margin:8px 0}p{color:#697782;line-height:1.7}.warning{margin:18px 0;padding:12px;border:1px solid #f1c477;border-radius:8px;background:#fff8e9;color:#915600}button{height:42px;padding:0 18px;border:0;border-radius:8px;background:#ff9810;font-weight:900}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:22px 0}.stats article{display:grid;gap:5px;padding:14px;border:1px solid #e1e7eb;border-radius:8px}.stats b{font-size:24px}.stats span{color:#7d8992}table{width:100%;border-collapse:collapse}th,td{padding:10px;border:1px solid #e5eaed;font-size:11px;text-align:left}th{background:#f4f7f9}em{padding:4px 7px;border-radius:9px;font-style:normal}.migrate{background:#e4f6eb;color:#15804b}.review{background:#fff0d7;color:#a96300}.exclude{background:#eef1f3;color:#68757e}.download{margin-top:20px}.error{color:#c43b32}@media(max-width:750px){main{padding:15px}section{padding:20px}.stats{grid-template-columns:1fr 1fr}table{display:block;overflow:auto}}</style>
