package com.milano.quotation.imports;

import com.fasterxml.jackson.databind.node.ObjectNode;import com.milano.quotation.purchase.PurchaseProductService;import com.milano.quotation.storage.AssetStorageService;import org.springframework.scheduling.annotation.Async;import org.springframework.stereotype.Service;import java.io.*;import java.time.Instant;import java.util.*;import java.util.zip.ZipEntry;import java.util.zip.ZipInputStream;

@Service
public class ImageMigrationProcessor{
    private static final long MAX_ENTRY=20L*1024*1024,MAX_TOTAL=500L*1024*1024*1024;private static final int MAX_ENTRIES=100_000,MAX_COMPRESSION_RATIO=100;
    private final ImportJobRepository jobs;private final ImportPartRepository parts;private final MigrationManifestEntryRepository entries;private final AssetStorageService storage;private final ImageMigrationFinalizer finalizer;private final PurchaseProductService products;
    public ImageMigrationProcessor(ImportJobRepository jobs,ImportPartRepository parts,MigrationManifestEntryRepository entries,AssetStorageService storage,ImageMigrationFinalizer finalizer,PurchaseProductService products){this.jobs=jobs;this.parts=parts;this.entries=entries;this.storage=storage;this.finalizer=finalizer;this.products=products;}
    @Async public void process(UUID jobId){var job=jobs.findById(jobId).orElseThrow();long total=0;int count=0;try{for(var part:parts.findByJobIdOrderByPartNumber(jobId)){try(var zip=new ZipInputStream(new BufferedInputStream(storage.openRaw(part.objectKey)))){ZipEntry entry;while((entry=zip.getNextEntry())!=null){if(entry.isDirectory())continue;if(++count>MAX_ENTRIES)throw new IOException("ZIP条目数量超过限制");if(entry.getSize()>0&&entry.getCompressedSize()>0&&entry.getSize()/entry.getCompressedSize()>MAX_COMPRESSION_RATIO)throw new IOException("ZIP条目压缩比例超过安全限制");var name=normalize(entry.getName());var manifest=entries.findByJobIdAndFileName(jobId,name).orElse(null);if(manifest==null){drain(zip,MAX_ENTRY);continue;}try{var bytes=readBounded(zip,MAX_ENTRY);total+=bytes.length;if(total>MAX_TOTAL)throw new IOException("解压后总大小超过500GB限制");var sha=AssetStorageService.sha256(bytes);if(manifest.expectedSha256!=null&&!manifest.expectedSha256.equals(sha))throw new IOException("SHA256不匹配");if(!products.exists(manifest.sku))throw new IOException("SKU不存在，已进入孤立报告");var asset=storage.storeImage(bytes,name);manifest.assetId=asset.id;manifest.status="validated";manifest.errorMessage=null;}catch(Exception failure){manifest.status="failed";manifest.errorMessage=safeMessage(failure);}manifest.updatedAt=Instant.now();entries.save(manifest);}}}var pending=entries.countByJobIdAndStatus(jobId,"pending");var failed=entries.countByJobIdAndStatus(jobId,"failed");if(pending==0&&failed==0){finalizer.publish(jobId);return;}job.status="completed-with-errors";job.completedAt=Instant.now();}catch(Exception fatal){job.status="failed";job.errorMessage=safeMessage(fatal);}job.updatedAt=Instant.now();var payload=(ObjectNode)job.payload;payload.put("completed",entries.countByJobIdAndStatus(jobId,"completed"));payload.put("validated",entries.countByJobIdAndStatus(jobId,"validated"));payload.put("failed",entries.countByJobIdAndStatus(jobId,"failed"));payload.put("pending",entries.countByJobIdAndStatus(jobId,"pending"));jobs.save(job);}
    private static byte[] readBounded(InputStream input,long max)throws IOException{var out=new ByteArrayOutputStream();var buffer=new byte[8192];long total=0;int read;while((read=input.read(buffer))!=-1){total+=read;if(total>max)throw new IOException("单张图片超过20MB");out.write(buffer,0,read);}return out.toByteArray();}
    private static void drain(InputStream input,long max)throws IOException{var buffer=new byte[8192];long total=0;int read;while((read=input.read(buffer))!=-1){total+=read;if(total>max)throw new IOException("未登记ZIP条目超过20MB");}}
    private static String normalize(String value)throws IOException{var path=value.replace('\\','/').replaceAll("^\\./","");if(path.startsWith("/")||path.matches("^[A-Za-z]:.*")||Arrays.asList(path.split("/")).contains("..")||path.length()>512)throw new IOException("ZIP包含不安全路径");return path;}
    private static String safeMessage(Exception e){var value=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();return value.substring(0,Math.min(1000,value.length()));}
}
