package com.milano.quotation.imports;

import com.fasterxml.jackson.databind.ObjectMapper;import com.fasterxml.jackson.databind.node.ObjectNode;import com.milano.quotation.common.AppException;import com.milano.quotation.storage.AssetStorageService;import org.apache.poi.ss.usermodel.DataFormatter;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import org.springframework.scheduling.annotation.Async;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;import java.io.*;import java.security.MessageDigest;import java.time.Instant;import java.util.*;import java.util.zip.ZipEntry;import java.util.zip.ZipInputStream;

@Service
public class ImageMigrationService{
    private static final List<String> HEADERS=List.of("SKU","图片类型","文件名","SHA256");private static final long MAX_PART=512L*1024*1024,MAX_ENTRY=20L*1024*1024,MAX_UNCOMPRESSED=5L*1024*1024*1024;
    private final ImportJobRepository jobs;private final MigrationManifestEntryRepository entries;private final ImportPartRepository parts;private final AssetStorageService storage;private final ObjectMapper mapper;
    public ImageMigrationService(ImportJobRepository jobs,MigrationManifestEntryRepository entries,ImportPartRepository parts,AssetStorageService storage,ObjectMapper mapper){this.jobs=jobs;this.entries=entries;this.parts=parts;this.storage=storage;this.mapper=mapper;}
    @Transactional public ImportJob create(MultipartFile manifest,String actor){if(manifest.isEmpty()||manifest.getOriginalFilename()==null||!manifest.getOriginalFilename().toLowerCase(Locale.ROOT).endsWith(".xlsx"))throw AppException.unprocessable("迁移清单必须是 .xlsx 文件");if(manifest.getSize()>20L*1024*1024)throw AppException.unprocessable("迁移清单不能超过20MB");try(var workbook=new XSSFWorkbook(manifest.getInputStream())){var sheet=workbook.getSheetAt(0);var formatter=new DataFormatter(Locale.CHINA);for(int i=0;i<HEADERS.size();i++)if(!HEADERS.get(i).equals(formatter.formatCellValue(sheet.getRow(0).getCell(i)).trim()))throw AppException.unprocessable("清单表头必须依次为 SKU、图片类型、文件名、SHA256");var job=new ImportJob();job.id=UUID.randomUUID();job.jobType="purchase-image-migration";job.status="awaiting-parts";job.requestedBy=actor;job.sourceName=safeName(manifest.getOriginalFilename());job.sourceHash=sha(manifest);job.createdAt=Instant.now();job.updatedAt=job.createdAt;var payload=mapper.createObjectNode();payload.put("manifestRows",0);payload.put("uploadedParts",0);payload.put("completed",0);payload.put("failed",0);job.payload=payload;jobs.save(job);var list=new ArrayList<MigrationManifestEntry>();var names=new HashSet<String>();for(int i=1;i<=sheet.getLastRowNum();i++){var row=sheet.getRow(i);if(row==null)continue;var sku=formatter.formatCellValue(row.getCell(0)).trim().toUpperCase(Locale.ROOT).replaceAll("\\s+","");var type=formatter.formatCellValue(row.getCell(1)).trim();var file=normalizePath(formatter.formatCellValue(row.getCell(2)).trim());var expected=formatter.formatCellValue(row.getCell(3)).trim().toLowerCase(Locale.ROOT);if(sku.isBlank()&&file.isBlank())continue;if(sku.isBlank()||!List.of("产品图","实物图","product","physical").contains(type)||file.isBlank())throw AppException.unprocessable("清单第"+(i+1)+"行的 SKU、图片类型或文件名不合法");if(!expected.isBlank()&&!expected.matches("[0-9a-f]{64}"))throw AppException.unprocessable("清单第"+(i+1)+"行 SHA256 格式不合法");if(!names.add(file))throw AppException.conflict("清单内文件名重复："+file);var entry=new MigrationManifestEntry();entry.id=UUID.randomUUID();entry.jobId=job.id;entry.sku=sku;entry.imageType=type.equals("产品图")?"product":type.equals("实物图")?"physical":type;entry.fileName=file;entry.expectedSha256=expected.isBlank()?null:expected;entry.status="pending";entry.updatedAt=Instant.now();list.add(entry);if(list.size()>200_000)throw AppException.unprocessable("单个迁移任务最多20万条图片关系");}entries.saveAll(list);payload.put("manifestRows",list.size());var objectKey="migration/"+job.id+"/manifest.xlsx";storage.putRaw(objectKey,manifest.getInputStream(),manifest.getSize(),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");return job;}catch(AppException e){throw e;}catch(Exception e){throw AppException.unprocessable("迁移清单解析失败");}}
    @Transactional public ImportPart uploadPart(UUID jobId,int partNumber,MultipartFile file){var job=jobs.findById(jobId).orElseThrow(()->AppException.notFound("迁移任务不存在"));if(!List.of("awaiting-parts","uploading").contains(job.status))throw AppException.conflict("当前任务不能继续上传分卷");if(partNumber<1||partNumber>10000)throw AppException.unprocessable("分卷编号不合法");if(file.isEmpty()||file.getOriginalFilename()==null||!file.getOriginalFilename().toLowerCase(Locale.ROOT).endsWith(".zip"))throw AppException.unprocessable("分卷必须是独立 ZIP 文件");if(file.getSize()>MAX_PART)throw AppException.unprocessable("单个ZIP分卷不能超过512MB");if(parts.findByJobIdAndPartNumber(jobId,partNumber).isPresent())throw AppException.conflict("该分卷编号已经上传");try{var objectKey="migration/"+jobId+"/parts/"+String.format("%05d",partNumber)+".zip";storage.putRaw(objectKey,file.getInputStream(),file.getSize(),"application/zip");var part=new ImportPart();part.id=UUID.randomUUID();part.jobId=jobId;part.partNumber=partNumber;part.objectKey=objectKey;part.sha256=sha(file);part.sizeBytes=file.getSize();part.originalName=safeName(file.getOriginalFilename());part.createdAt=Instant.now();parts.save(part);job.status="uploading";job.updatedAt=Instant.now();((ObjectNode)job.payload).put("uploadedParts",parts.findByJobIdOrderByPartNumber(jobId).size());return part;}catch(Exception e){if(e instanceof AppException app)throw app;throw AppException.unprocessable("ZIP分卷读取失败");}}
    @Transactional public void markProcessing(UUID jobId){var job=jobs.findById(jobId).orElseThrow(()->AppException.notFound("迁移任务不存在"));if(!job.status.equals("uploading")||parts.findByJobIdOrderByPartNumber(jobId).isEmpty())throw AppException.conflict("请先上传至少一个ZIP分卷");job.status="processing";job.updatedAt=Instant.now();}
    public JobView view(UUID jobId){var job=jobs.findById(jobId).orElseThrow(()->AppException.notFound("迁移任务不存在"));return new JobView(job.id,job.status,job.sourceName,job.payload,entries.countByJobIdAndStatus(jobId,"completed"),entries.countByJobIdAndStatus(jobId,"failed"),entries.countByJobIdAndStatus(jobId,"pending"),parts.findByJobIdOrderByPartNumber(jobId).size(),job.errorMessage,job.createdAt,job.updatedAt);}
    public java.util.List<ErrorView> errors(UUID jobId){if(!jobs.existsById(jobId))throw AppException.notFound("迁移任务不存在");return entries.findByJobIdOrderByFileName(jobId).stream().filter(row->"failed".equals(row.status)).map(row->new ErrorView(row.sku,row.imageType,row.fileName,row.errorMessage)).toList();}
    private static String normalizePath(String value){var path=value.replace('\\','/').replaceAll("^\\./","");if(path.startsWith("/")||path.matches("^[A-Za-z]:.*")||Arrays.asList(path.split("/")).contains("..")||path.length()>512)throw AppException.unprocessable("清单包含不安全的文件路径");return path;}
    private static String sha(MultipartFile file)throws Exception{try(var input=file.getInputStream()){var digest=MessageDigest.getInstance("SHA-256");input.transferTo(new java.security.DigestOutputStream(OutputStream.nullOutputStream(),digest));return HexFormat.of().formatHex(digest.digest());}}
    private static String safeName(String name){var value=name.replaceAll("[\\r\\n\\\\/]","_");return value.substring(0,Math.min(255,value.length()));}
    public record JobView(UUID id,String status,String sourceName,com.fasterxml.jackson.databind.JsonNode summary,long completed,long failed,long pending,int uploadedParts,String error,Instant createdAt,Instant updatedAt){}
    public record ErrorView(String sku,String imageType,String fileName,String error){}
}
