package com.milano.quotation.imports;

import tools.jackson.databind.ObjectMapper;import com.milano.quotation.audit.AuditService;import com.milano.quotation.common.ApiResponse;import com.milano.quotation.idempotency.IdempotencyService;import com.milano.quotation.security.QuotationPrincipal;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.util.Map;import java.util.UUID;

@RestController @RequestMapping("/api/v1/migration-jobs") @PreAuthorize("hasAuthority('PERM_purchase')")
public class ImageMigrationController{
    private final ImageMigrationService migration;private final ImageMigrationProcessor processor;private final AuditService audit;private final IdempotencyService idempotency;private final ObjectMapper mapper;public ImageMigrationController(ImageMigrationService migration,ImageMigrationProcessor processor,AuditService audit,IdempotencyService idempotency,ObjectMapper mapper){this.migration=migration;this.processor=processor;this.audit=audit;this.idempotency=idempotency;this.mapper=mapper;}
    @PostMapping(consumes="multipart/form-data")ApiResponse<?>create(@RequestPart("manifest")MultipartFile manifest,Authentication auth){var job=migration.create(manifest,account(auth));audit.record("migration.create","migration-job",job.id.toString(),"success",Map.of("source",job.sourceName));return ApiResponse.ok(migration.view(job.id));}
    @PutMapping(value="/{id}/parts/{partNumber}",consumes="multipart/form-data")ApiResponse<?>part(@PathVariable UUID id,@PathVariable int partNumber,@RequestPart("file")MultipartFile file){var result=migration.uploadPart(id,partNumber,file);audit.record("migration.part-upload","migration-job",id.toString(),"success",Map.of("part",partNumber,"size",result.sizeBytes));return ApiResponse.ok(migration.view(id));}
    @PostMapping("/{id}/complete")ApiResponse<?>complete(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,Authentication auth){var request=mapper.createObjectNode().put("jobId",id.toString());var existing=idempotency.existing(account(auth),"migration-complete",key,request);if(existing.isPresent())return ApiResponse.ok(existing.get());migration.markProcessing(id);processor.process(id);var response=mapper.valueToTree(migration.view(id));idempotency.save(account(auth),"migration-complete",key,request,response);audit.record("migration.process","migration-job",id.toString(),"success",Map.of());return ApiResponse.ok(response);}
    @GetMapping("/{id}")ApiResponse<?>get(@PathVariable UUID id){return ApiResponse.ok(migration.view(id));}
    @GetMapping("/{id}/errors")ApiResponse<?>errors(@PathVariable UUID id){return ApiResponse.ok(migration.errors(id));}
    private static String account(Authentication auth){return((QuotationPrincipal)auth.getPrincipal()).account();}
}
