package com.milano.quotation.imports;

import com.fasterxml.jackson.databind.JsonNode;import com.milano.quotation.audit.AuditService;import com.milano.quotation.common.ApiResponse;import com.milano.quotation.common.AppException;import com.milano.quotation.idempotency.IdempotencyService;import com.milano.quotation.purchase.PurchaseProductService;import com.milano.quotation.security.QuotationPrincipal;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import java.time.Instant;import java.util.*;

@RestController @RequestMapping("/api/v1/purchase-imports") @PreAuthorize("hasAuthority('PERM_purchase')")
public class PurchaseImportController{
    private final PurchaseWorkbookService parser;private final ImportJobRepository jobs;private final PurchaseImportRowRepository rows;private final PurchaseProductService products;private final IdempotencyService idempotency;private final AuditService audit;
    public PurchaseImportController(PurchaseWorkbookService parser,ImportJobRepository jobs,PurchaseImportRowRepository rows,PurchaseProductService products,IdempotencyService idempotency,AuditService audit){this.parser=parser;this.jobs=jobs;this.rows=rows;this.products=products;this.idempotency=idempotency;this.audit=audit;}
    @PostMapping(value="/preview",consumes="multipart/form-data")ApiResponse<?>preview(@RequestPart("file")MultipartFile file,Authentication auth){var result=parser.preview(file,account(auth));audit.record("purchase.import-preview","purchase-import",result.jobId().toString(),"success",Map.of("file",result.fileName(),"rows",result.records().size()));return ApiResponse.ok(result);}
    @GetMapping("/{id}")@Transactional(readOnly=true)ApiResponse<?>job(@PathVariable UUID id){var job=jobs.findById(id).orElseThrow(()->AppException.notFound("导入任务不存在"));return ApiResponse.ok(Map.of("id",job.id,"status",job.status,"sourceName",job.sourceName,"summary",job.payload,"records",rows.findByJobIdOrderBySourceRow(id).stream().map(r->r.payload).toList()));}
    @PostMapping("/{id}/confirm")@Transactional ApiResponse<?>confirm(@PathVariable UUID id,@RequestHeader("Idempotency-Key")String key,Authentication auth){var job=jobs.findById(id).orElseThrow(()->AppException.notFound("导入任务不存在"));var request=com.fasterxml.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("jobId",id.toString());var existing=idempotency.existing(account(auth),"purchase-import-confirm",key,request);if(existing.isPresent())return ApiResponse.ok(existing.get());if(!job.status.equals("preview"))throw AppException.conflict("该导入任务不能再次确认");var imported=new ArrayList<JsonNode>();for(var row:rows.findByJobIdOrderBySourceRow(id))imported.add(products.upsertImported(row.payload,row.productAssetId,row.physicalAssetId));job.status="completed";job.updatedAt=Instant.now();job.completedAt=job.updatedAt;var response=com.fasterxml.jackson.databind.node.JsonNodeFactory.instance.objectNode().put("jobId",id.toString()).put("imported",imported.size()).put("status","completed");idempotency.save(account(auth),"purchase-import-confirm",key,request,response);audit.record("purchase.import-confirm","purchase-import",id.toString(),"success",Map.of("count",imported.size()));return ApiResponse.ok(response);}
    private static String account(Authentication auth){return((QuotationPrincipal)auth.getPrincipal()).account();}
}
