package com.milano.quotation.imports;

import com.fasterxml.jackson.databind.ObjectMapper;import com.fasterxml.jackson.databind.node.ArrayNode;import com.fasterxml.jackson.databind.node.ObjectNode;import com.milano.quotation.common.AppException;import com.milano.quotation.purchase.PurchaseProductRepository;import com.milano.quotation.storage.AssetStorageService;import org.apache.poi.ss.usermodel.*;import org.apache.poi.xssf.usermodel.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;
import java.io.InputStream;import java.math.BigDecimal;import java.math.RoundingMode;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;

@Service
public class PurchaseWorkbookService{
    public static final List<String> HEADERS=List.of("SKU*","类别*","产品图片（嵌入本格）","实物图（嵌入本格）","报价人*","报价日期*","尺码","颜色","克重(g)*","长(cm)*","宽(cm)*","高(cm)*","起订量(件)*","基准采购单价(CNY/件)*","阶梯价2起订量","阶梯价2(CNY/件)","阶梯价3起订量","阶梯价3(CNY/件)","1件总运费(CNY)","10件总运费(CNY)","100件总运费(CNY)","是否包邮","含票价(CNY/件)","票类型","是否有货*","备注","工厂信息","货源链接1","货源链接2","货源链接3","相似货源","审核备注");
    private final ImportJobRepository jobs;private final PurchaseImportRowRepository rows;private final PurchaseProductRepository products;private final AssetStorageService storage;private final ObjectMapper mapper;
    public PurchaseWorkbookService(ImportJobRepository jobs,PurchaseImportRowRepository rows,PurchaseProductRepository products,AssetStorageService storage,ObjectMapper mapper){this.jobs=jobs;this.rows=rows;this.products=products;this.storage=storage;this.mapper=mapper;}
    @Transactional public Preview preview(MultipartFile file,String actor){
        if(file.isEmpty()||file.getOriginalFilename()==null||!file.getOriginalFilename().toLowerCase(Locale.ROOT).endsWith(".xlsx"))throw AppException.unprocessable("请选择 .xlsx 格式的采购模板");if(file.getSize()>30L*1024*1024)throw AppException.unprocessable("Excel 文件不能超过30MB");
        try(var workbook=new XSSFWorkbook(file.getInputStream())){var sheet=workbook.getSheet("采购产品导入");if(sheet==null)throw AppException.unprocessable("没有找到工作表“采购产品导入”");validateHeaders(sheet);var pictures=pictures(sheet);var issues=mapper.createArrayNode();var parsed=new ArrayList<ParsedRow>();var seen=new HashSet<String>();int skipped=0,generated=0,productImages=0,physicalImages=0;var now=LocalDateTime.now(ZoneId.of("Asia/Shanghai"));
            for(int index=1;index<=sheet.getLastRowNum();index++){var row=sheet.getRow(index);int excelRow=index+1;if(empty(row)&&!pictures.containsKey(excelRow+":2")&&!pictures.containsKey(excelRow+":3"))continue;var sku=text(row,0).toUpperCase(Locale.ROOT).replaceAll("\\s+","");var warnings=mapper.createArrayNode();if(sku.isBlank()){sku="AUTO-"+now.format(DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss"))+"-R"+excelRow;generated++;issue(issues,excelRow,"SKU*","SKU 为空，已生成 "+sku+"，必须修改后才能参与报价","warning");warnings.add("SKU为空，必须修改后才能参与报价");}if(!seen.add(sku)){issue(issues,excelRow,"SKU*","同一文件内 SKU "+sku+" 重复，本行已跳过","skipped");skipped++;continue;}var payload=record(row,excelRow,sku,warnings,issues);UUID productAsset=null,physicalAsset=null;var productPicture=pictures.get(excelRow+":2");if(productPicture!=null){var asset=storage.storeImage(productPicture.getData(),sku+"-product."+productPicture.suggestFileExtension());productAsset=asset.id;payload.put("productImage","/api/v1/assets/"+asset.id);payload.put("image","/api/v1/assets/"+asset.id);productImages++;}var physicalPicture=pictures.get(excelRow+":3");if(physicalPicture!=null){var asset=storage.storeImage(physicalPicture.getData(),sku+"-physical."+physicalPicture.suggestFileExtension());physicalAsset=asset.id;payload.put("physicalImage","/api/v1/assets/"+asset.id);physicalImages++;}parsed.add(new ParsedRow(excelRow,sku,payload,productAsset,physicalAsset));}
            var job=new ImportJob();job.id=UUID.randomUUID();job.jobType="purchase-xlsx";job.status="preview";job.requestedBy=actor;job.sourceName=safeName(file.getOriginalFilename());job.sourceHash=sha(file);var summary=mapper.createObjectNode();summary.put("totalRows",parsed.size()+skipped);summary.put("added",parsed.stream().filter(r->!products.findBySku(r.sku()).isPresent()).count());summary.put("updated",parsed.stream().filter(r->products.findBySku(r.sku()).isPresent()).count());summary.put("generatedSku",generated);summary.put("productImages",productImages);summary.put("physicalImages",physicalImages);summary.put("skipped",skipped);summary.set("issues",issues);job.payload=summary;job.createdAt=Instant.now();job.updatedAt=job.createdAt;jobs.save(job);var saved=new ArrayList<PurchaseImportRow>();for(var parsedRow:parsed){var entity=new PurchaseImportRow();entity.id=UUID.randomUUID();entity.jobId=job.id;entity.sourceRow=parsedRow.sourceRow();entity.sku=parsedRow.sku();entity.payload=parsedRow.payload();entity.productAssetId=parsedRow.productAssetId();entity.physicalAssetId=parsedRow.physicalAssetId();entity.createdAt=Instant.now();saved.add(entity);}rows.saveAll(saved);return new Preview(job.id,job.sourceName,parsed.stream().map(ParsedRow::payload).toList(),issues,summary);
        }catch(AppException e){throw e;}catch(Exception e){throw AppException.unprocessable("Excel 文件解析失败："+safeMessage(e));}}
    private void validateHeaders(Sheet sheet){var row=sheet.getRow(0);var mismatch=new ArrayList<String>();for(int i=0;i<HEADERS.size();i++){if(!HEADERS.get(i).equals(text(row,i)))mismatch.add(column(i)+"列应为“"+HEADERS.get(i)+"”");}if(!mismatch.isEmpty())throw AppException.unprocessable("模板列头不匹配："+String.join("；",mismatch.subList(0,Math.min(4,mismatch.size())))+(mismatch.size()>4?"…":""));}
    private Map<String,XSSFPictureData> pictures(XSSFSheet sheet){var result=new HashMap<String,XSSFPictureData>();var drawing=sheet.getDrawingPatriarch();if(drawing==null)return result;for(var shape:drawing.getShapes()){if(shape instanceof XSSFPicture picture){var anchor=picture.getClientAnchor();int col=anchor.getCol1(),row=anchor.getRow1()+1;if((col==2||col==3)&&row>=2)result.put(row+":"+col,picture.getPictureData());}}return result;}
    private ObjectNode record(Row row,int sourceRow,String sku,ArrayNode warnings,ArrayNode issues){var object=mapper.createObjectNode();object.put("sourceRow",sourceRow);object.put("sku",sku);object.put("skuOrigin",sku.startsWith("AUTO-")?"system":"imported");object.put("category",text(row,1));object.put("productImage","");object.put("physicalImage","");object.put("quotationOwner",text(row,4));object.put("quotationDate",date(row==null?null:row.getCell(5),sourceRow,issues));object.put("size",text(row,6));object.put("color",text(row,7));putNumber(object,"weightG",number(row,8,sourceRow,"克重(g)*",issues));putNumber(object,"lengthCm",number(row,9,sourceRow,"长(cm)*",issues));putNumber(object,"widthCm",number(row,10,sourceRow,"宽(cm)*",issues));putNumber(object,"heightCm",number(row,11,sourceRow,"高(cm)*",issues));putNumber(object,"minOrderQty",integer(row,12,sourceRow,"起订量(件)*",issues));putNumber(object,"purchasePriceCny",number(row,13,sourceRow,"基准采购单价(CNY/件)*",issues));putNumber(object,"tier2MinQty",integer(row,14,sourceRow,"阶梯价2起订量",issues));putNumber(object,"tier2PriceCny",number(row,15,sourceRow,"阶梯价2(CNY/件)",issues));putNumber(object,"tier3MinQty",integer(row,16,sourceRow,"阶梯价3起订量",issues));putNumber(object,"tier3PriceCny",number(row,17,sourceRow,"阶梯价3(CNY/件)",issues));putNumber(object,"singleFreightCny",number(row,18,sourceRow,"1件总运费(CNY)",issues));putNumber(object,"freight10Cny",number(row,19,sourceRow,"10件总运费(CNY)",issues));putNumber(object,"freight100Cny",number(row,20,sourceRow,"100件总运费(CNY)",issues));object.put("freeShipping",choice(text(row,21),Set.of("是","否"),sourceRow,"是否包邮",issues));putNumber(object,"taxIncludedPriceCny",number(row,22,sourceRow,"含票价(CNY/件)",issues));object.put("invoiceType",text(row,23));object.put("stockStatus",choice(text(row,24),Set.of("有货","无货","待确认"),sourceRow,"是否有货*",issues));object.put("notes",text(row,25));object.put("factoryInfo",text(row,26));object.put("sourceLink1",text(row,27));object.put("sourceLink2",text(row,28));object.put("sourceLink3",text(row,29));object.put("similarSource",text(row,30));object.put("auditNotes",text(row,31));object.set("importWarnings",warnings);normalizeAliases(object);return object;}
    private void normalizeAliases(ObjectNode o){var sku=o.path("sku").asText();var category=o.path("category").asText();var weight=o.get("weightG");var min=o.get("minOrderQty");var price=o.get("purchasePriceCny");boolean ready=!sku.startsWith("AUTO-")&&positive(weight)&&positive(min)&&price!=null&&!price.isNull()&&price.asDouble()>=0;o.put("quoteReady",ready);o.put("status",sku.startsWith("AUTO-")?"系统生成SKU，待修改":ready?"资料完整":"待补充资料");o.put("name",category.isBlank()?"商品 "+sku:category);o.put("image",o.path("productImage").asText());if(weight==null||weight.isNull()){o.putNull("weightKg");o.put("weightDescription","");}else{o.put("weightKg",weight.asDouble()/1000);o.put("weightDescription",weight.asText());}o.put("colorSku",o.path("color").asText());for(var field:List.of("material","marks","rawTierPrice","l6Price","freightTrial","invoiceInfo","taxPoint","otherNotes","more"))o.put(field,"");o.putArray("shippingMarks");o.put("taxIncludedPrice",o.path("taxIncludedPriceCny").isNumber()?o.path("taxIncludedPriceCny").asText():"");o.put("taxDifference",o.path("invoiceType").asText());o.put("packagingInfo",o.path("factoryInfo").asText());var links=o.putArray("sourceLinks");links.add(o.path("sourceLink1").asText());links.add(o.path("sourceLink2").asText());links.add(o.path("sourceLink3").asText());links.add(o.path("similarSource").asText());var tiers=o.putArray("priceTiers");var candidates=new ArrayList<double[]>();addTier(candidates,o,"minOrderQty","purchasePriceCny");addTier(candidates,o,"tier2MinQty","tier2PriceCny");addTier(candidates,o,"tier3MinQty","tier3PriceCny");candidates.sort(Comparator.comparingDouble(a->a[0]));for(int i=0;i<candidates.size();i++){var tier=tiers.addObject();tier.put("minQty",(long)candidates.get(i)[0]);if(i+1<candidates.size())tier.put("maxQty",(long)candidates.get(i+1)[0]-1);else tier.putNull("maxQty");tier.put("unitPriceCny",candidates.get(i)[1]);tier.put("source",i==0?"基准采购单价":"阶梯价"+(i+1));}}
    private static void addTier(List<double[]>list,ObjectNode o,String qty,String price){if(positive(o.get(qty))&&o.get(price)!=null&&!o.get(price).isNull()&&o.get(price).asDouble()>=0)list.add(new double[]{o.get(qty).asDouble(),o.get(price).asDouble()});}
    private static boolean positive(com.fasterxml.jackson.databind.JsonNode n){return n!=null&&!n.isNull()&&n.asDouble()>0;}
    private static void putNumber(ObjectNode o,String key,BigDecimal value){if(value==null)o.putNull(key);else o.put(key,value);}
    private static String text(Row row,int cell){if(row==null)return"";return new DataFormatter(Locale.CHINA).formatCellValue(row.getCell(cell)).trim();}
    private static boolean empty(Row row){if(row==null)return true;for(int i=0;i<HEADERS.size();i++)if(!text(row,i).isBlank())return false;return true;}
    private static BigDecimal number(Row row,int cell,int sourceRow,String field,ArrayNode issues){var value=text(row,cell);if(value.isBlank())return null;try{var n=new BigDecimal(value);if(n.signum()<0)throw new NumberFormatException();return n;}catch(Exception e){issue(issues,sourceRow,field,"“"+value+"”不是有效非负数字，已留空","warning");return null;}}
    private static BigDecimal integer(Row row,int cell,int sourceRow,String field,ArrayNode issues){var n=number(row,cell,sourceRow,field,issues);return n==null?null:n.setScale(0,RoundingMode.FLOOR);}
    private static String choice(String value,Set<String>allowed,int row,String field,ArrayNode issues){if(value.isBlank())return"";if(allowed.contains(value))return value;issue(issues,row,field,"“"+value+"”不在可选值中，已留空","warning");return"";}
    private static String date(Cell cell,int row,ArrayNode issues){if(cell==null)return"";try{if(cell.getCellType()==CellType.NUMERIC&&DateUtil.isCellDateFormatted(cell))return cell.getLocalDateTimeCellValue().toLocalDate().toString();var value=new DataFormatter(Locale.CHINA).formatCellValue(cell).trim().replace('/','-').replace('.','-');if(value.isBlank())return"";return LocalDate.parse(value).toString();}catch(Exception e){issue(issues,row,"报价日期*","无法识别日期，已留空","warning");return"";}}
    private static void issue(ArrayNode issues,int row,String field,String message,String level){var item=issues.addObject();item.put("row",row);item.put("field",field);item.put("message",message);item.put("level",level);}
    private static String column(int index){StringBuilder s=new StringBuilder();for(int v=index+1;v>0;v=(v-1)/26)s.insert(0,(char)('A'+(v-1)%26));return s.toString();}
    private static String sha(MultipartFile file)throws Exception{try(InputStream input=file.getInputStream()){var digest=java.security.MessageDigest.getInstance("SHA-256");input.transferTo(new java.security.DigestOutputStream(java.io.OutputStream.nullOutputStream(),digest));return java.util.HexFormat.of().formatHex(digest.digest());}}
    private static String safeName(String value){return value.replaceAll("[\\r\\n\\\\/]","_").substring(0,Math.min(255,value.length()));}
    private static String safeMessage(Exception e){var message=e.getMessage();return message==null?e.getClass().getSimpleName():message.substring(0,Math.min(200,message.length()));}
    private record ParsedRow(int sourceRow,String sku,ObjectNode payload,UUID productAssetId,UUID physicalAssetId){}
    public record Preview(UUID jobId,String fileName,List<ObjectNode>records,ArrayNode issues,ObjectNode summary){}
}
