package com.milano.quotation.logistics;

import com.milano.quotation.common.AppException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.node.JsonNodeFactory;

import java.time.Instant;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

class LogisticsServiceTest {
    private LogisticsProviderRepository providers;private LogisticsChannelRepository channels;private LogisticsVersionRepository versions;private LogisticsService service;private final Map<UUID,LogisticsProviderEntity> providerRows=new LinkedHashMap<>();private final Map<UUID,LogisticsChannelEntity> channelRows=new LinkedHashMap<>();private final Map<UUID,LogisticsVersionEntity> versionRows=new LinkedHashMap<>();
    @BeforeEach void setup(){providers=mock(LogisticsProviderRepository.class);channels=mock(LogisticsChannelRepository.class);versions=mock(LogisticsVersionRepository.class);service=new LogisticsService(providers,channels,versions);when(providers.save(any())).thenAnswer(c->{var row=(LogisticsProviderEntity)c.getArgument(0);providerRows.put(row.id,row);return row;});when(channels.save(any())).thenAnswer(c->{var row=(LogisticsChannelEntity)c.getArgument(0);channelRows.put(row.id,row);return row;});when(channels.saveAndFlush(any())).thenAnswer(c->{var row=(LogisticsChannelEntity)c.getArgument(0);channelRows.put(row.id,row);return row;});when(versions.save(any())).thenAnswer(c->{var row=(LogisticsVersionEntity)c.getArgument(0);versionRows.put(row.id,row);return row;});when(providers.findById(any())).thenAnswer(c->Optional.ofNullable(providerRows.get(c.getArgument(0))));when(channels.findById(any())).thenAnswer(c->Optional.ofNullable(channelRows.get(c.getArgument(0))));when(versions.findById(any())).thenAnswer(c->Optional.ofNullable(versionRows.get(c.getArgument(0))));when(providers.existsById(any())).thenAnswer(c->providerRows.containsKey(c.getArgument(0)));when(channels.existsById(any())).thenAnswer(c->channelRows.containsKey(c.getArgument(0)));when(providers.findAllByOrderByUpdatedAtDesc()).thenAnswer(c->new ArrayList<>(providerRows.values()));when(channels.findAllByOrderByUpdatedAtDesc()).thenAnswer(c->new ArrayList<>(channelRows.values()));when(versions.findAllByOrderByCreatedAtDesc()).thenAnswer(c->new ArrayList<>(versionRows.values()));when(channels.findAll()).thenAnswer(c->new ArrayList<>(channelRows.values()));when(versions.findByChannelIdOrderByVersionNumberDesc(any())).thenAnswer(c->versionRows.values().stream().filter(v->v.channelId.equals(c.getArgument(0))).toList());when(channels.countByProviderId(any())).thenAnswer(c->channelRows.values().stream().filter(v->v.providerId.equals(c.getArgument(0))).count());doAnswer(c->{versionRows.remove(((LogisticsVersionEntity)c.getArgument(0)).id);return null;}).when(versions).delete(any());doAnswer(c->{channelRows.remove((UUID)c.getArgument(0));return null;}).when(channels).deleteById(any());doAnswer(c->{providerRows.remove((UUID)c.getArgument(0));return null;}).when(providers).deleteById(any());}
    @Test void addsProviderAndChannelAndReturnsWorkspace(){var provider=service.addProvider(JsonNodeFactory.instance.objectNode().put("name","云途").put("code","yt"));var providerId=UUID.fromString(provider.path("id").asText());var channel=service.addChannel(JsonNodeFactory.instance.objectNode().put("providerId",providerId.toString()).put("name","云途普货").put("code","yt-ph"));assertEquals("YT",provider.path("code").asText());assertEquals("YT-PH",channel.path("code").asText());assertEquals(1,service.workspace().providers().size());assertEquals(1,service.workspace().channels().size());}
    @Test void validatesProviderAndChannelConflicts(){assertThrows(AppException.class,()->service.addProvider(JsonNodeFactory.instance.objectNode().put("name","").put("code","X")));when(providers.existsByCodeIgnoreCase("YT")).thenReturn(true);assertThrows(AppException.class,()->service.addProvider(JsonNodeFactory.instance.objectNode().put("name","云途").put("code","YT")));assertThrows(AppException.class,()->service.addChannel(JsonNodeFactory.instance.objectNode().put("providerId",UUID.randomUUID().toString()).put("name","渠道").put("code","C")));}
    @Test void updatesEnablesClonesAndDeletesChannelsWithOptimisticLock(){var provider=provider("P","物流商");var channel=channel(provider,"C","渠道");channel.version=2;assertThrows(AppException.class,()->service.updateChannel(channel.id,JsonNodeFactory.instance.objectNode().put("code","C").put("name","新名称"),1));var updated=service.updateChannel(channel.id,JsonNodeFactory.instance.objectNode().put("code","C").put("name","新名称").put("enabled",false),2);assertEquals("新名称",updated.path("name").asText());assertThrows(AppException.class,()->service.setChannelEnabled(channel.id,true,1));assertTrue(service.setChannelEnabled(channel.id,true,2).path("enabled").asBoolean());service.deleteChannel(channel.id);verify(channels).delete(channel);}
    @Test void blocksDeleteAndCreatesValidatedManualDraft(){var provider=provider("P","物流商");var channel=channel(provider,"C","渠道");var published=version(channel,"published","HASH1",rows());channel.currentVersionId=published.id;assertThrows(AppException.class,()->service.deleteChannel(channel.id));var invalid=JsonNodeFactory.instance.objectNode();invalid.putArray("rows").addObject().put("areaName","美国").put("weightFromKg",2).put("weightToKg",1);assertThrows(AppException.class,()->service.createManualDraft(channel.id,invalid));var body=JsonNodeFactory.instance.objectNode();body.set("rows",rows());var draft=service.createManualDraft(channel.id,body);assertEquals("draft",draft.path("status").asText());assertEquals(2,draft.path("versionNumber").asInt());}
    @Test void publishesAndRollsBackWithAllGuards(){var provider=provider("P","物流商");var channel=channel(provider,"C","渠道");var draft=version(channel,"draft","HASH1",rows());assertThrows(AppException.class,()->service.publish(channel.id,draft.id,"","ADMIN",true));((tools.jackson.databind.node.ObjectNode)draft.payload).put("errors",1);assertThrows(AppException.class,()->service.publish(channel.id,draft.id,"审核","ADMIN",true));((tools.jackson.databind.node.ObjectNode)draft.payload).put("errors",0).putObject("summary").put("removed",1);assertThrows(AppException.class,()->service.publish(channel.id,draft.id,"审核","ADMIN",false));var published=service.publish(channel.id,draft.id,"审核通过","ADMIN",true);assertEquals("published",published.path("status").asText());assertEquals(draft.id,channel.currentVersionId);var rolled=service.rollback(channel.id,draft.id,"回滚测试","ADMIN");assertEquals("published",rolled.path("status").asText());assertEquals(2,rolled.path("versionNumber").asInt());}
    @Test void importsMigrationDraftsIdempotentlyAndRollsThemBack(){var entries=JsonNodeFactory.instance.arrayNode();var entry=entries.addObject();var value=entry.put("category","logistics").putObject("value");value.put("providerName","云途").put("providerCode","YUNTU").put("channelName","云途普货").put("channelCode","SUMAO-1").put("sourceHash","a".repeat(64)).put("fileName","云途普货.xlsx");value.set("rows",rows());value.putArray("issues");value.putObject("summary").put("added",1);var result=service.importMigrationDrafts(entries,"ADMIN");assertEquals(1,result.path("providersCreated").asInt());assertEquals(1,result.path("channelsCreated").asInt());assertEquals(1,result.path("versionsCreated").asInt());var execution=JsonNodeFactory.instance.objectNode().set("logistics",result);var rollback=service.rollbackMigration(execution);assertEquals(1,rollback.path("versionsRemoved").asInt());assertEquals(1,rollback.path("channelsRemoved").asInt());assertEquals(1,rollback.path("providersRemoved").asInt());}
    private LogisticsProviderEntity provider(String code,String name){var row=new LogisticsProviderEntity();row.id=UUID.randomUUID();row.code=code;row.createdAt=Instant.now();row.updatedAt=row.createdAt;row.payload=JsonNodeFactory.instance.objectNode().put("id",row.id.toString()).put("code",code).put("name",name).put("enabled",true);providerRows.put(row.id,row);when(providers.findByCodeIgnoreCase(code)).thenReturn(Optional.of(row));return row;}
    private LogisticsChannelEntity channel(LogisticsProviderEntity provider,String code,String name){var row=new LogisticsChannelEntity();row.id=UUID.randomUUID();row.providerId=provider.id;row.code=code;row.ruleId=channelRows.size()+1;row.createdAt=Instant.now();row.updatedAt=row.createdAt;row.payload=JsonNodeFactory.instance.objectNode().put("id",row.id.toString()).put("providerId",provider.id.toString()).put("code",code).put("name",name).put("enabled",true).put("currentVersionId","");channelRows.put(row.id,row);when(channels.findByCodeIgnoreCase(code)).thenReturn(Optional.of(row));return row;}
    private LogisticsVersionEntity version(LogisticsChannelEntity channel,String status,String hash,tools.jackson.databind.node.ArrayNode rows){var row=new LogisticsVersionEntity();row.id=UUID.randomUUID();row.channelId=channel.id;row.versionNumber=(int)versionRows.values().stream().filter(v->v.channelId.equals(channel.id)).count()+1;row.status=status;row.sourceHash=hash;row.createdAt=Instant.now();row.payload=JsonNodeFactory.instance.objectNode().put("id",row.id.toString()).put("channelId",channel.id.toString()).put("versionNumber",row.versionNumber).put("status",status).put("sourceHash",hash).put("fileName","source.xlsx").put("errors",0).set("rows",rows);((tools.jackson.databind.node.ObjectNode)row.payload).putObject("summary").put("removed",0);versionRows.put(row.id,row);when(versions.findByChannelIdAndSourceHash(channel.id,hash)).thenReturn(Optional.of(row));return row;}
    private tools.jackson.databind.node.ArrayNode rows(){var rows=JsonNodeFactory.instance.arrayNode();rows.addObject().put("areaName","美国").put("countryCode","US").put("weightFromKg",0).put("weightToKg",2).put("pricePerKg",55);return rows;}
}
