<script setup lang="ts">
import type { QuotationMode } from './types'

withDefaults(defineProps<{ mode: QuotationMode; skuSearch: string; customerName: string; productCategory: string; productCategories: readonly string[]; monthlySalesEstimate: string; attributes: string[]; logisticsAttribute: string; grades: Array<{ grade: string }>; grade: string; coefficient: number; salesperson: string; invalidFields?: string[] }>(), { invalidFields: () => [] })
defineEmits<{ 'update:mode': [value: QuotationMode]; 'update:skuSearch': [value: string]; 'update:customerName': [value: string]; 'update:productCategory': [value: string]; 'update:monthlySalesEstimate': [value: string]; query: []; 'update:logisticsAttribute': [value: string]; 'update:grade': [value: string] }>()
</script>

<template>
  <section class="condition-card">
    <header><div><b><i>01</i> 报价条件</b><span>系统自动匹配采购成本，并在报价矩阵中生成可用渠道</span></div><p><span>当前报价业务员</span><strong>{{ salesperson }}</strong><em>登录账号自动带出</em></p></header>
    <div class="condition-grid" :class="{ bundle: mode === 'bundle' }">
      <label class="customer-field" data-validation-field="customerName" :class="{ invalid:invalidFields.includes('customerName') }"><span>客户名称 <em>保存必填</em></span><input :value="customerName" placeholder="输入客户名称" @input="$emit('update:customerName', ($event.target as HTMLInputElement).value)"><small v-if="invalidFields.includes('customerName')" class="field-error">请填写客户名称</small></label>
      <label class="mode-field"><span>报价模式</span><select :value="mode" @change="$emit('update:mode', ($event.target as HTMLSelectElement).value as QuotationMode)"><option value="single">单品 SKU 报价</option><option value="bundle">组合 SKU 报价</option></select></label>
      <label v-if="mode === 'single'" class="sku-field" data-validation-field="sku" :class="{ invalid:invalidFields.includes('sku') }"><span>SKU</span><div class="sku-input"><i>⌕</i><input :value="skuSearch" placeholder="输入 SKU" @input="$emit('update:skuSearch', ($event.target as HTMLInputElement).value)" @keyup.enter="$emit('query')"></div><small v-if="invalidFields.includes('sku')" class="field-error">请输入并查询有效 SKU</small></label>
      <label class="logistics-field"><span>物流属性</span><select :value="logisticsAttribute" @change="$emit('update:logisticsAttribute', ($event.target as HTMLSelectElement).value)"><option v-for="attribute in attributes" :key="attribute">{{ attribute }}</option></select></label>
      <label class="grade-field"><span>客户等级</span><select :value="grade" @change="$emit('update:grade', ($event.target as HTMLSelectElement).value)"><option v-for="setting in grades" :key="setting.grade" :value="setting.grade">{{ setting.grade }}级客户</option></select><small>报价系数 {{ coefficient.toFixed(2) }}</small></label>
      <label class="category-field" data-validation-field="productCategory" :class="{ invalid:invalidFields.includes('productCategory') }"><span>产品品类 <em>保存必填</em></span><select :value="productCategory" @change="$emit('update:productCategory', ($event.target as HTMLSelectElement).value)"><option value="" disabled>请选择产品品类</option><option v-for="category in productCategories" :key="category" :value="category">{{ category }}</option></select><small v-if="invalidFields.includes('productCategory')" class="field-error">请选择产品品类</small></label>
      <label class="sales-field"><span>预估月销量</span><select :value="monthlySalesEstimate" @change="$emit('update:monthlySalesEstimate', ($event.target as HTMLSelectElement).value)"><option value="10">预估月销量 10</option><option value="100">预估月销量 100</option><option value="100+">预估月销量 100+</option></select></label>
    </div>
    <footer><span>{{ mode === 'bundle' ? '在组合明细中逐个查询 SKU，物流属性由本次组合统一选择。' : '查询后将刷新商品成本、重量及下方渠道报价矩阵。' }}</span><button v-if="mode === 'single'" @click="$emit('query')">查询商品</button></footer>
  </section>
</template>

<style scoped>
.condition-card{padding:20px 22px;border:1px solid #e3e8ed;border-radius:12px;background:#fff;box-shadow:0 7px 22px rgba(17,24,39,.04)}header{display:flex;align-items:center;justify-content:space-between;gap:20px;padding-bottom:15px;border-bottom:1px solid #edf0f3}header>div{display:grid;gap:4px}header b{display:flex;align-items:center;gap:9px;font-size:16px}header b i{width:27px;height:27px;display:grid;place-items:center;border-radius:7px;background:#fff1dc;color:#b96800;font-size:10px;font-style:normal}header>div>span{color:#8a959f;font-size:11px}header p{display:flex;align-items:center;gap:8px;margin:0;font-size:11px}header p span{color:#8b959e}header p strong{color:#27333d}header p em{padding:4px 8px;border-radius:12px;background:#eef7f1;color:#208358;font-size:9px;font-style:normal}.condition-grid{display:grid;grid-template-columns:1fr 1.35fr 1.2fr 1fr 1fr;gap:16px;margin-top:17px}.condition-grid.bundle{grid-template-columns:repeat(4,1fr)}.condition-grid label{display:grid;align-content:start;gap:7px;min-width:0;color:#66737e;font-size:11px}.condition-grid label span em{margin-left:4px;color:#bc6b00;font-size:9px;font-style:normal}.condition-grid input,.condition-grid select{width:100%;height:40px;box-sizing:border-box;border:1px solid #d9e0e6;border-radius:7px;background:#fff;padding:0 11px;color:#202c36;font-size:13px;outline:0}.condition-grid input:focus,.condition-grid select:focus{border-color:#f3a12d;box-shadow:0 0 0 3px rgba(255,153,0,.11)}.condition-grid small{color:#a36b1e;font-size:10px}.sku-input{position:relative}.sku-input i{position:absolute;left:11px;top:50%;transform:translateY(-50%);color:#7a8791;font-style:normal}.sku-input input{padding-left:31px}.condition-card footer{display:flex;align-items:center;justify-content:flex-end;gap:16px;margin-top:16px;padding-top:14px;border-top:1px solid #edf0f3}.condition-card footer span{color:#8c97a1;font-size:11px}.condition-card footer button{height:38px;min-width:116px;border:0;border-radius:7px;background:#17232d;color:#fff;font-size:12px;font-weight:800}@media(max-width:1100px){.condition-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){header{align-items:flex-start;flex-direction:column}.condition-grid,.condition-grid.bundle{grid-template-columns:1fr 1fr}.condition-card footer{align-items:stretch;flex-direction:column}.condition-card footer button{width:100%}}@media(max-width:500px){.condition-grid,.condition-grid.bundle{grid-template-columns:1fr}}
.condition-card{padding:18px 20px}.condition-card header{padding-bottom:13px}.condition-grid{grid-template-columns:1fr 1.12fr 1.18fr 1fr 1fr 1.08fr;gap:10px;margin-top:14px}.condition-grid.bundle{grid-template-columns:repeat(5,1fr)}.condition-grid label{gap:6px;font-size:10px}.condition-grid input,.condition-grid select{height:36px;padding:0 9px;font-size:12px}.sku-input i{left:10px}.sku-input input{padding-left:28px}.condition-card footer{gap:14px;margin-top:13px;padding-top:12px}@media(max-width:1100px){.condition-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.condition-grid,.condition-grid.bundle{grid-template-columns:1fr 1fr}}@media(max-width:500px){.condition-grid,.condition-grid.bundle{grid-template-columns:1fr}}
.condition-grid{grid-template-columns:repeat(7,minmax(0,1fr));gap:9px}.condition-grid.bundle{grid-template-columns:repeat(6,minmax(0,1fr))}@media(max-width:1100px){.condition-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:900px){.condition-grid,.condition-grid.bundle{grid-template-columns:1fr 1fr}}@media(max-width:500px){.condition-grid,.condition-grid.bundle{grid-template-columns:1fr}}
.condition-grid,.condition-grid.bundle{grid-template-columns:repeat(4,minmax(0,1fr));column-gap:14px;row-gap:12px}.customer-field{grid-column:1}.mode-field{grid-column:2}.sku-field{grid-column:3}.category-field{grid-column:4}.logistics-field{grid-column:1;grid-row:2}.grade-field{grid-column:2;grid-row:2}.sales-field{grid-column:3;grid-row:2}.condition-grid.bundle .category-field{grid-column:3}.condition-grid.bundle .logistics-field{grid-column:1;grid-row:2}.condition-grid.bundle .grade-field{grid-column:2;grid-row:2}.condition-grid.bundle .sales-field{grid-column:3;grid-row:2}@media(max-width:1100px){.condition-grid,.condition-grid.bundle{grid-template-columns:repeat(3,minmax(0,1fr))}.condition-grid label,.condition-grid.bundle label{grid-column:auto;grid-row:auto}.category-field{grid-column:1!important;grid-row:2!important}}@media(max-width:900px){.condition-grid,.condition-grid.bundle{grid-template-columns:1fr 1fr}.condition-grid label,.condition-grid.bundle label,.category-field{grid-column:auto!important;grid-row:auto!important}}@media(max-width:500px){.condition-grid,.condition-grid.bundle{grid-template-columns:1fr}}
.condition-grid label.invalid input,.condition-grid label.invalid select{border-color:#e2523f;background:#fff8f6;box-shadow:0 0 0 3px rgba(226,82,63,.09)}.condition-grid .field-error{color:#c43f31;font-size:9px;font-weight:750}
</style>
